# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class BlockAnimateRandomTickEvent(object):
    """ [客户端] 触发时机：以摄像机为中心，随机选取周围的方块触发Tick，触发的数量取决于设备性能。只有添加了netease:block_animate_random_tick的自定义方块才会触发此事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockPos(self):
        # type: () -> tuple[float, float, float]
        """ 方块坐标 """
        return self.mArgs.get("blockPos")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

class BlockDestroyByLiquidServerEvent(object):
    """ [服务端] 触发时机：方块被水流破坏的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def liquidName(self):
        # type: () -> str
        """ 流体方块id """
        return self.mArgs.get("liquidName")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块id """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 方块所在维度id """
        return self.mArgs.get("dimensionId")

class BlockLiquidStateChangeAfterServerEvent(object):
    """ [服务端] 触发时机：方块转为含水或者脱离含水(流体)后触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def turnLiquid(self):
        # type: () -> bool
        """ 是否转为含水，true则转为含水，false则脱离含水 """
        return self.mArgs.get("turnLiquid")

class BlockLiquidStateChangeServerEvent(object):
    """ [服务端] 触发时机：方块转为含水或者脱离含水(流体)前触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def turnLiquid(self):
        # type: () -> bool
        """ 是否转为含水，true则转为含水，false则脱离含水 """
        return self.mArgs.get("turnLiquid")

class BlockNeighborChangedServerEvent(object):
    """ [服务端] 触发时机：自定义方块周围的方块发生变化时，需要配置netease:neighborchanged_sendto_script，详情请查阅《自定义农作物》文档 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度 """
        return self.mArgs.get("dimensionId")

    @property
    def posX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def neighborPosX(self):
        # type: () -> int
        """ 变化方块x坐标 """
        return self.mArgs.get("neighborPosX")

    @property
    def neighborPosY(self):
        # type: () -> int
        """ 变化方块y坐标 """
        return self.mArgs.get("neighborPosY")

    @property
    def neighborPosZ(self):
        # type: () -> int
        """ 变化方块z坐标 """
        return self.mArgs.get("neighborPosZ")

    @property
    def fromBlockName(self):
        # type: () -> str
        """ 方块变化前的identifier，包含命名空间及名称 """
        return self.mArgs.get("fromBlockName")

    @property
    def fromBlockAuxValue(self):
        # type: () -> int
        """ 方块变化前附加值 """
        return self.mArgs.get("fromBlockAuxValue")

    @property
    def toBlockName(self):
        # type: () -> str
        """ 方块变化后的identifier，包含命名空间及名称 """
        return self.mArgs.get("toBlockName")

    @property
    def toAuxValue(self):
        # type: () -> int
        """ 方块变化后附加值 """
        return self.mArgs.get("toAuxValue")

class BlockRandomTickServerEvent(object):
    """ [服务端] 触发时机：自定义方块配置netease:random_tick随机tick时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def posX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块名称 """
        return self.mArgs.get("blockName")

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("fullName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def brightness(self):
        # type: () -> int
        """ 方块亮度 """
        return self.mArgs.get("brightness")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 方块所在维度 """
        return self.mArgs.get("dimensionId")

class BlockRemoveServerEvent(object):
    """ [服务端] 触发时机：监听该事件的方块在销毁时触发，可以通过ListenOnBlockRemoveEvent方法进行监听，或者通过json组件netease:listen_block_remove进行配置 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("z")

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("fullName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimension(self):
        # type: () -> int
        """ 该方块所在的维度 """
        return self.mArgs.get("dimension")

class BlockSnowStateChangeAfterServerEvent(object):
    """ [服务端] 触发时机：方块转为含雪或者脱离含雪后触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def turnSnow(self):
        # type: () -> bool
        """ 是否转为含雪，true则转为含雪，false则脱离含雪 """
        return self.mArgs.get("turnSnow")

    @property
    def setBlockType(self):
        # type: () -> int
        """ 方块进入脱离含雪的原因，参考SetBlockType """
        return self.mArgs.get("setBlockType")

class BlockSnowStateChangeServerEvent(object):
    """ [服务端] 触发时机：方块转为含雪或者脱离含雪前触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def turnSnow(self):
        # type: () -> bool
        """ 是否转为含雪，true则转为含雪，false则脱离含雪 """
        return self.mArgs.get("turnSnow")

    @property
    def setBlockType(self):
        # type: () -> int
        """ 方块进入脱离含雪的原因，参考SetBlockType """
        return self.mArgs.get("setBlockType")

class BlockStrengthChangedServerEvent(object):
    """ [服务端] 触发时机：自定义机械元件方块红石信号量发生变化时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def posX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxValue")

    @property
    def newStrength(self):
        # type: () -> int
        """ 变化后的红石信号量 """
        return self.mArgs.get("newStrength")

    @property
    def oldStrength(self):
        # type: () -> int
        """ 变化前的红石信号量 """
        return self.mArgs.get("oldStrength")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度 """
        return self.mArgs.get("dimensionId")

class ChestBlockTryPairWithServerEvent(object):
    """ [服务端] 触发时机：两个并排的小箱子方块准备组合为一个大箱子方块时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止小箱子组合成为一个大箱子 """
        return self.mArgs.get("cancel")

    @property
    def blockX(self):
        # type: () -> int
        """ 小箱子方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 小箱子方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 小箱子方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def otherBlockX(self):
        # type: () -> int
        """ 将要与之组合的另外一个小箱子方块x坐标 """
        return self.mArgs.get("otherBlockX")

    @property
    def otherBlockY(self):
        # type: () -> int
        """ 将要与之组合的另外一个小箱子方块y坐标 """
        return self.mArgs.get("otherBlockY")

    @property
    def otherBlockZ(self):
        # type: () -> int
        """ 将要与之组合的另外一个小箱子方块z坐标 """
        return self.mArgs.get("otherBlockZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class ClientBlockUseEvent(object):
    """ [客户端] 触发时机：玩家右键点击新版自定义方块（或者通过接口AddBlockItemListenForUseEvent增加监听的MC原生游戏方块）时客户端抛出该事件（该事件tick执行，需要注意效率问题）。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def aux(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("aux")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截与方块交互的逻辑。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

class CommandBlockContainerOpenEvent(object):
    """ [服务端] 触发时机：玩家点击命令方块，尝试打开命令方块的设置界面 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def isBlock(self):
        # type: () -> bool
        """ 是否以方块坐标的形式定位命令方块，当为True时下述的blockX/blockY/blockZ有意义，当为False时，下述的victimId有意义 """
        return self.mArgs.get("isBlock")

    @property
    def blockX(self):
        # type: () -> int
        """ 命令方块位置x，当isBlock为True时有效 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 命令方块位置y，当isBlock为True时有效 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 命令方块位置z，当isBlock为True时有效 """
        return self.mArgs.get("blockZ")

    @property
    def victimId(self):
        # type: () -> str
        """ 命令方块对应的逻辑实体的唯一id，当isBlock为False时有效 """
        return self.mArgs.get("victimId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可以阻止玩家打开命令方块的设置界面 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class CommandBlockUpdateEvent(object):
    """ [服务端] 触发时机：玩家尝试修改命令方块的内置命令时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def playerUid(self):
        # type: () -> int
        """ 玩家的uid """
        return self.mArgs.get("playerUid")

    @property
    def command(self):
        # type: () -> str
        """ 企图修改的命令方块中的命令内容字符串 """
        return self.mArgs.get("command")

    @command.setter
    def command(self, value):
        self.mArgs["command"] = value

    @property
    def isBlock(self):
        # type: () -> bool
        """ 是否以方块坐标的形式定位命令方块，当为True时下述的blockX/blockY/blockZ有意义，当为False时，下述的victimId有意义 """
        return self.mArgs.get("isBlock")

    @property
    def blockX(self):
        # type: () -> int
        """ 命令方块位置x，当isBlock为True时有效 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 命令方块位置y，当isBlock为True时有效 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 命令方块位置z，当isBlock为True时有效 """
        return self.mArgs.get("blockZ")

    @property
    def victimId(self):
        # type: () -> str
        """ 命令方块对应的逻辑实体的唯一id，当isBlock为False时有效 """
        return self.mArgs.get("victimId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可以阻止玩家修改命令方块的内置命令 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class DestroyBlockEvent(object):
    """ [服务端] 触发时机：当方块已经被玩家破坏时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def face(self):
        # type: () -> int
        """ 方块被敲击的面向id，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("fullName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def playerId(self):
        # type: () -> str
        """ 破坏方块的玩家ID """
        return self.mArgs.get("playerId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def dropEntityIds(self):
        # type: () -> list[str]
        """ 掉落物实体id列表 """
        return self.mArgs.get("dropEntityIds")

class DirtBlockToGrassBlockServerEvent(object):
    """ [服务端] 触发时机：泥土方块变成草方块时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

class EntityPlaceBlockAfterServerEvent(object):
    """ [服务端] 触发时机：当生物成功放置方块后触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("fullName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def entityId(self):
        # type: () -> str
        """ 试图放置方块的生物ID """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

class FallingBlockBreakServerEvent(object):
    """ [服务端] 触发时机：当下落的方块实体被破坏时，服务端触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def fallingBlockId(self):
        # type: () -> str
        """ 下落的方块实体id """
        return self.mArgs.get("fallingBlockId")

    @property
    def fallingBlockX(self):
        # type: () -> float
        """ 下落的方块实体位置x """
        return self.mArgs.get("fallingBlockX")

    @property
    def fallingBlockY(self):
        # type: () -> float
        """ 下落的方块实体位置y """
        return self.mArgs.get("fallingBlockY")

    @property
    def fallingBlockZ(self):
        # type: () -> float
        """ 下落的方块实体位置z """
        return self.mArgs.get("fallingBlockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 重力方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def fallTickAmount(self):
        # type: () -> int
        """ 下落的方块实体持续下落了多少tick """
        return self.mArgs.get("fallTickAmount")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 下落的方块实体维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancelDrop(self):
        # type: () -> bool
        """ 是否取消方块物品掉落，可以在脚本层中设置 """
        return self.mArgs.get("cancelDrop")

    @cancelDrop.setter
    def cancelDrop(self, value):
        self.mArgs["cancelDrop"] = value

class FallingBlockCauseDamageBeforeClientEvent(object):
    """ [客户端] 触发时机：当下落的方块开始计算砸到实体的伤害时，客户端触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def fallingBlockId(self):
        # type: () -> int
        """ 下落的方块实体id """
        return self.mArgs.get("fallingBlockId")

    @property
    def fallingBlockX(self):
        # type: () -> float
        """ 下落的方块实体位置x """
        return self.mArgs.get("fallingBlockX")

    @property
    def fallingBlockY(self):
        # type: () -> float
        """ 下落的方块实体位置y """
        return self.mArgs.get("fallingBlockY")

    @property
    def fallingBlockZ(self):
        # type: () -> float
        """ 下落的方块实体位置z """
        return self.mArgs.get("fallingBlockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 重力方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 下落的方块实体维度id """
        return self.mArgs.get("dimensionId")

    @property
    def collidingEntitys(self):
        # type: () -> list[str]
        """ 当前碰撞到的实体列表id（客户端只能获取到玩家），如果没有的话是None """
        return self.mArgs.get("collidingEntitys")

    @property
    def fallTickAmount(self):
        # type: () -> int
        """ 下落的方块实体持续下落了多少tick """
        return self.mArgs.get("fallTickAmount")

    @property
    def fallDistance(self):
        # type: () -> float
        """ 下落的方块实体持续下落了多少距离 """
        return self.mArgs.get("fallDistance")

    @property
    def isHarmful(self):
        # type: () -> bool
        """ 客户端始终为false，因为客户端不会计算伤害值 """
        return self.mArgs.get("isHarmful")

    @property
    def fallDamage(self):
        # type: () -> int
        """ 对实体的伤害 """
        return self.mArgs.get("fallDamage")

class FallingBlockCauseDamageBeforeServerEvent(object):
    """ [服务端] 触发时机：当下落的方块开始计算砸到实体的伤害时，服务端触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def fallingBlockId(self):
        # type: () -> str
        """ 下落的方块实体id """
        return self.mArgs.get("fallingBlockId")

    @property
    def fallingBlockX(self):
        # type: () -> float
        """ 下落的方块实体位置x """
        return self.mArgs.get("fallingBlockX")

    @property
    def fallingBlockY(self):
        # type: () -> float
        """ 下落的方块实体位置y """
        return self.mArgs.get("fallingBlockY")

    @property
    def fallingBlockZ(self):
        # type: () -> float
        """ 下落的方块实体位置z """
        return self.mArgs.get("fallingBlockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 重力方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 下落的方块实体维度id """
        return self.mArgs.get("dimensionId")

    @property
    def collidingEntitys(self):
        # type: () -> list[str]
        """ 当前碰撞到的实体列表id，如果没有的话是None """
        return self.mArgs.get("collidingEntitys")

    @property
    def fallTickAmount(self):
        # type: () -> int
        """ 下落的方块实体持续下落了多少tick """
        return self.mArgs.get("fallTickAmount")

    @property
    def fallDistance(self):
        # type: () -> float
        """ 下落的方块实体持续下落了多少距离 """
        return self.mArgs.get("fallDistance")

    @property
    def isHarmful(self):
        # type: () -> bool
        """ 是否计算对实体的伤害，引擎传来的值由json配置和伤害是否大于0决定，可在脚本层修改传回引擎 """
        return self.mArgs.get("isHarmful")

    @isHarmful.setter
    def isHarmful(self, value):
        self.mArgs["isHarmful"] = value

    @property
    def fallDamage(self):
        # type: () -> int
        """ 对实体的伤害，引擎传来的值距离和json配置决定，可在脚本层修改传回引擎 """
        return self.mArgs.get("fallDamage")

    @fallDamage.setter
    def fallDamage(self, value):
        self.mArgs["fallDamage"] = value

class FallingBlockReturnHeavyBlockServerEvent(object):
    """ [服务端] 触发时机：当下落的方块实体变回普通重力方块时，服务端触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def fallingBlockId(self):
        # type: () -> int
        """ 下落的方块实体id """
        return self.mArgs.get("fallingBlockId")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def heavyBlockName(self):
        # type: () -> str
        """ 重力方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("heavyBlockName")

    @property
    def prevHereBlockName(self):
        # type: () -> str
        """ 变回重力方块时，原本方块位置的identifier，包含命名空间及名称 """
        return self.mArgs.get("prevHereBlockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 下落的方块实体维度id """
        return self.mArgs.get("dimensionId")

    @property
    def fallTickAmount(self):
        # type: () -> int
        """ 下落的方块实体持续下落了多少tick """
        return self.mArgs.get("fallTickAmount")

class FarmBlockToDirtBlockServerEvent(object):
    """ [服务端] 触发时机：耕地退化为泥土时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def setBlockType(self):
        # type: () -> int
        """ 耕地退化为泥土的原因，参考SetBlockType """
        return self.mArgs.get("setBlockType")

class GrassBlockToDirtBlockServerEvent(object):
    """ [服务端] 触发时机：草方块变成泥土方块时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 方块维度 """
        return self.mArgs.get("dimension")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

class HeavyBlockStartFallingServerEvent(object):
    """ [服务端] 触发时机：当重力方块变为下落的方块实体后，服务端触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def fallingBlockId(self):
        # type: () -> str
        """ 下落的方块实体id """
        return self.mArgs.get("fallingBlockId")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 重力方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 下落的方块实体维度id """
        return self.mArgs.get("dimensionId")

class HopperTryPullInServerEvent(object):
    """ [服务端] 触发时机：当漏斗上方连接容器后，容器往漏斗开始输入物品时触发，事件仅触发一次 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 漏斗位置x """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 漏斗位置y """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 漏斗位置z """
        return self.mArgs.get("z")

    @property
    def abovePosX(self):
        # type: () -> int
        """ 交互的容器位置x """
        return self.mArgs.get("abovePosX")

    @property
    def abovePosY(self):
        # type: () -> int
        """ 交互的容器位置y """
        return self.mArgs.get("abovePosY")

    @property
    def abovePosZ(self):
        # type: () -> int
        """ 交互的容器位置z """
        return self.mArgs.get("abovePosZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def canHopper(self):
        # type: () -> bool
        """ 是否允许容器往漏斗加东西(要关闭此交互，需先监听此事件再放置容器) """
        return self.mArgs.get("canHopper")

class HopperTryPullOutServerEvent(object):
    """ [服务端] 触发时机：当漏斗以毗邻的方式连接容器时，即从旁边连接容器时，漏斗向容器开始输出物品时触发，事件仅触发一次 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 漏斗位置x """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 漏斗位置y """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 漏斗位置z """
        return self.mArgs.get("z")

    @property
    def attachedPosX(self):
        # type: () -> int
        """ 交互的容器位置x """
        return self.mArgs.get("attachedPosX")

    @property
    def attachedPosY(self):
        # type: () -> int
        """ 交互的容器位置y """
        return self.mArgs.get("attachedPosY")

    @property
    def attachedPosZ(self):
        # type: () -> int
        """ 交互的容器位置z """
        return self.mArgs.get("attachedPosZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def canHopper(self):
        # type: () -> bool
        """ 是否允许漏斗往容器加东西(要关闭此交互，需先监听此事件再放置容器) """
        return self.mArgs.get("canHopper")

class ModBlockEntityLoadedClientEvent(object):
    """ [客户端] 客户端自定义方块实体初始化完成时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def posX(self):
        # type: () -> int
        """ 自定义方块实体的位置X """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 自定义方块实体的位置Y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 自定义方块实体的位置Z """
        return self.mArgs.get("posZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

class ModBlockEntityRemoveClientEvent(object):
    """ [客户端] 客户端自定义方块实体卸载时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def posX(self):
        # type: () -> int
        """ 自定义方块实体的位置X """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 自定义方块实体的位置Y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 自定义方块实体的位置Z """
        return self.mArgs.get("posZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

class ModBlockEntityTickClientEvent(object):
    """ [客户端] 客户端自定义方块实体tick事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def posX(self):
        # type: () -> int
        """ 自定义方块实体的位置X """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 自定义方块实体的位置Y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 自定义方块实体的位置Z """
        return self.mArgs.get("posZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

class OnAfterFallOnBlockClientEvent(object):
    """ [客户端] 触发时机：当实体降落到方块后客户端触发，主要用于力的计算 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def posX(self):
        # type: () -> float
        """ 实体位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 实体位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 实体位置z """
        return self.mArgs.get("posZ")

    @property
    def motionX(self):
        # type: () -> float
        """ 瞬时移动X方向的力 """
        return self.mArgs.get("motionX")

    @property
    def motionY(self):
        # type: () -> float
        """ 瞬时移动Y方向的力 """
        return self.mArgs.get("motionY")

    @property
    def motionZ(self):
        # type: () -> float
        """ 瞬时移动Z方向的力 """
        return self.mArgs.get("motionZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def calculate(self):
        # type: () -> bool
        """ 是否按脚本层传值计算力 """
        return self.mArgs.get("calculate")

class OnAfterFallOnBlockServerEvent(object):
    """ [服务端] 触发时机：当实体降落到方块后服务端触发，主要用于力的计算 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def posX(self):
        # type: () -> float
        """ 实体位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 实体位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 实体位置z """
        return self.mArgs.get("posZ")

    @property
    def motionX(self):
        # type: () -> float
        """ 瞬时移动X方向的力 """
        return self.mArgs.get("motionX")

    @property
    def motionY(self):
        # type: () -> float
        """ 瞬时移动Y方向的力 """
        return self.mArgs.get("motionY")

    @property
    def motionZ(self):
        # type: () -> float
        """ 瞬时移动Z方向的力 """
        return self.mArgs.get("motionZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def calculate(self):
        # type: () -> bool
        """ 是否按脚本层传值计算力 """
        return self.mArgs.get("calculate")

class OnBeforeFallOnBlockServerEvent(object):
    """ [服务端] 触发时机：当实体刚降落到方块上时服务端触发，主要用于伤害计算 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def fallDistance(self):
        # type: () -> float
        """ 实体下降距离，可在脚本层传给引擎 """
        return self.mArgs.get("fallDistance")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消引擎对实体下降伤害的计算 """
        return self.mArgs.get("cancel")

class OnEntityInsideBlockClientEvent(object):
    """ [客户端] 触发时机：当实体碰撞盒所在区域有方块时，客户端持续触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 实体所在维度id """
        return self.mArgs.get("dimensionId")

    @property
    def slowdownMultiX(self):
        # type: () -> float
        """ 实体移速X方向的减速比例 """
        return self.mArgs.get("slowdownMultiX")

    @property
    def slowdownMultiY(self):
        # type: () -> float
        """ 实体移速Y方向的减速比例 """
        return self.mArgs.get("slowdownMultiY")

    @property
    def slowdownMultiZ(self):
        # type: () -> float
        """ 实体移速Z方向的减速比例 """
        return self.mArgs.get("slowdownMultiZ")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def cancel(self):
        # type: () -> bool
        """ 可由脚本层回传True给引擎，阻止触发后续原版逻辑 """
        return self.mArgs.get("cancel")

class OnEntityInsideBlockServerEvent(object):
    """ [服务端] 触发时机：当实体碰撞盒所在区域有方块时，服务端持续触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def slowdownMultiX(self):
        # type: () -> float
        """ 实体移速X方向的减速比例，可在脚本层被修改 """
        return self.mArgs.get("slowdownMultiX")

    @slowdownMultiX.setter
    def slowdownMultiX(self, value):
        self.mArgs["slowdownMultiX"] = value

    @property
    def slowdownMultiY(self):
        # type: () -> float
        """ 实体移速Y方向的减速比例，可在脚本层被修改 """
        return self.mArgs.get("slowdownMultiY")

    @slowdownMultiY.setter
    def slowdownMultiY(self, value):
        self.mArgs["slowdownMultiY"] = value

    @property
    def slowdownMultiZ(self):
        # type: () -> float
        """ 实体移速Z方向的减速比例，可在脚本层被修改 """
        return self.mArgs.get("slowdownMultiZ")

    @slowdownMultiZ.setter
    def slowdownMultiZ(self, value):
        self.mArgs["slowdownMultiZ"] = value

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def cancel(self):
        # type: () -> bool
        """ 可由脚本层回传True给引擎，阻止触发后续原版逻辑 """
        return self.mArgs.get("cancel")

class OnModBlockNeteaseEffectCreatedClientEvent(object):
    """ [客户端] 自定义方块实体绑定的特效创建成功事件，在自定义方块实体中绑定的特效创建成功时触发以及使用接口CreateFrameEffectForBlockEntity或CreateParticleEffectForBlockEntity为自定义方块实体添加特效成功时触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def effectName(self):
        # type: () -> str
        """ 创建成功的特效的自定义键值名称 """
        return self.mArgs.get("effectName")

    @property
    def id(self):
        # type: () -> int
        """ 该特效的id """
        return self.mArgs.get("id")

    @property
    def effectType(self):
        # type: () -> int
        """ 该特效的类型，0为粒子特效，1为序列帧特效 """
        return self.mArgs.get("effectType")

    @property
    def blockPos(self):
        # type: () -> tuple[float, float, float]
        """ 该特效绑定的自定义方块实体的世界坐标 """
        return self.mArgs.get("blockPos")

class OnStandOnBlockClientEvent(object):
    """ [客户端] 触发时机：当实体站立到方块上时客户端持续触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 实体所在维度id """
        return self.mArgs.get("dimensionId")

    @property
    def posX(self):
        # type: () -> float
        """ 实体位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 实体位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 实体位置z """
        return self.mArgs.get("posZ")

    @property
    def motionX(self):
        # type: () -> float
        """ 瞬时移动X方向的力 """
        return self.mArgs.get("motionX")

    @property
    def motionY(self):
        # type: () -> float
        """ 瞬时移动Y方向的力 """
        return self.mArgs.get("motionY")

    @property
    def motionZ(self):
        # type: () -> float
        """ 瞬时移动Z方向的力 """
        return self.mArgs.get("motionZ")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def cancel(self):
        # type: () -> bool
        """ 可由脚本层回传True给引擎，阻止触发后续原版逻辑 """
        return self.mArgs.get("cancel")

class OnStandOnBlockServerEvent(object):
    """ [服务端] 触发时机：当实体站立到方块上时服务端持续触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 实体所在维度id """
        return self.mArgs.get("dimensionId")

    @property
    def posX(self):
        # type: () -> float
        """ 实体位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 实体位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 实体位置z """
        return self.mArgs.get("posZ")

    @property
    def motionX(self):
        # type: () -> float
        """ 瞬时移动X方向的力 """
        return self.mArgs.get("motionX")

    @property
    def motionY(self):
        # type: () -> float
        """ 瞬时移动Y方向的力 """
        return self.mArgs.get("motionY")

    @property
    def motionZ(self):
        # type: () -> float
        """ 瞬时移动Z方向的力 """
        return self.mArgs.get("motionZ")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def cancel(self):
        # type: () -> bool
        """ 可由脚本层回传True给引擎，阻止触发后续原版逻辑 """
        return self.mArgs.get("cancel")

class PistonActionServerEvent(object):
    """ [服务端] 触发时机：活塞或者粘性活塞推送/缩回影响附近方块时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续的事件 """
        return self.mArgs.get("cancel")

    @property
    def action(self):
        # type: () -> str
        """ 推送时=expanding；缩回时=retracting """
        return self.mArgs.get("action")

    @property
    def pistonFacing(self):
        # type: () -> int
        """ 活塞的朝向，参考Facing枚举 """
        return self.mArgs.get("pistonFacing")

    @property
    def pistonMoveFacing(self):
        # type: () -> int
        """ 活塞的运动方向，参考Facing枚举 """
        return self.mArgs.get("pistonMoveFacing")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 活塞方块所在的维度 """
        return self.mArgs.get("dimensionId")

    @property
    def pistonX(self):
        # type: () -> int
        """ 活塞方块的x坐标 """
        return self.mArgs.get("pistonX")

    @property
    def pistonY(self):
        # type: () -> int
        """ 活塞方块的y坐标 """
        return self.mArgs.get("pistonY")

    @property
    def pistonZ(self):
        # type: () -> int
        """ 活塞方块的z坐标 """
        return self.mArgs.get("pistonZ")

    @property
    def blockList(self):
        # type: () -> list[list[float | int]]
        """ 活塞运动影响到产生被移动效果的方块坐标[x,y,z]，均为int类型 """
        return self.mArgs.get("blockList")

    @property
    def breakBlockList(self):
        # type: () -> list[list[float | int]]
        """ 活塞运动影响到产生被破坏效果的方块坐标[x,y,z]，均为int类型 """
        return self.mArgs.get("breakBlockList")

    @property
    def entityList(self):
        # type: () -> list[str]
        """ 活塞运动影响到产生被移动或被破坏效果的实体的ID列表 """
        return self.mArgs.get("entityList")

class PlayerTryDestroyBlockClientEvent(object):
    """ [客户端] 当玩家即将破坏方块时，客户端线程触发该事件。主要用于床，旗帜，箱子这些根据方块实体数据进行渲染的方块，一般情况下请使用ServerPlayerTryDestroyBlockEvent """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def face(self):
        # type: () -> int
        """ 方块被敲击的面向id，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def playerId(self):
        # type: () -> str
        """ 试图破坏方块的玩家ID """
        return self.mArgs.get("playerId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 默认为False，在脚本层设置为True就能取消该方块的破坏 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class ServerBlockEntityTickEvent(object):
    """ [服务端] 触发时机：自定义方块配置了netease:block_entity组件并设tick为true，方块在玩家的模拟距离（新建存档时可以设置，默认为4个区块）内，或者在tickingarea内的时候触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockName(self):
        # type: () -> str
        """ 该方块名称 """
        return self.mArgs.get("blockName")

    @property
    def dimension(self):
        # type: () -> int
        """ 该方块所在的维度 """
        return self.mArgs.get("dimension")

    @property
    def posX(self):
        # type: () -> int
        """ 该方块的x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 该方块的y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 该方块的z坐标 """
        return self.mArgs.get("posZ")

class ServerBlockUseEvent(object):
    """ [服务端] 触发时机：玩家右键点击新版自定义方块（或者通过接口AddBlockItemListenForUseEvent增加监听的MC原生游戏方块）时服务端抛出该事件（该事件tick执行，需要注意效率问题）。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def aux(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("aux")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截与方块交互的逻辑。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class ServerEntityTryPlaceBlockEvent(object):
    """ [服务端] 触发时机：当生物试图放置方块时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标,支持修改 """
        return self.mArgs.get("x")

    @x.setter
    def x(self, value):
        self.mArgs["x"] = value

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标,支持修改 """
        return self.mArgs.get("y")

    @y.setter
    def y(self, value):
        self.mArgs["y"] = value

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标,支持修改 """
        return self.mArgs.get("z")

    @z.setter
    def z(self, value):
        self.mArgs["z"] = value

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称,支持修改 """
        return self.mArgs.get("fullName")

    @fullName.setter
    def fullName(self, value):
        self.mArgs["fullName"] = value

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值,支持修改 """
        return self.mArgs.get("auxData")

    @auxData.setter
    def auxData(self, value):
        self.mArgs["auxData"] = value

    @property
    def entityId(self):
        # type: () -> str
        """ 试图放置方块的生物ID """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def cancel(self):
        # type: () -> bool
        """ 默认为False，在脚本层设置为True就能取消该方块的放置 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

class ServerPlaceBlockEntityEvent(object):
    """ [服务端] 触发时机：手动放置或通过接口创建含自定义方块实体的方块时触发，此时可向该方块实体中存放数据 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockName(self):
        # type: () -> str
        """ 该方块名称 """
        return self.mArgs.get("blockName")

    @property
    def dimension(self):
        # type: () -> int
        """ 该方块所在的维度 """
        return self.mArgs.get("dimension")

    @property
    def posX(self):
        # type: () -> int
        """ 该方块的x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 该方块的y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 该方块的z坐标 """
        return self.mArgs.get("posZ")

class ServerPlayerTryDestroyBlockEvent(object):
    """ [服务端] 当玩家即将破坏方块时，服务端线程触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def face(self):
        # type: () -> int
        """ 方块被敲击的面向id，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def fullName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("fullName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def playerId(self):
        # type: () -> str
        """ 试图破坏方块的玩家ID """
        return self.mArgs.get("playerId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 默认为False，在脚本层设置为True就能取消该方块的破坏 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def spawnResources(self):
        # type: () -> bool
        """ 是否生成掉落物，默认为True，在脚本层设置为False就能取消生成掉落物 """
        return self.mArgs.get("spawnResources")

    @spawnResources.setter
    def spawnResources(self, value):
        self.mArgs["spawnResources"] = value

class ShearsDestoryBlockBeforeClientEvent(object):
    """ [客户端] 触发时机：玩家手持剪刀破坏方块时，有剪刀特殊效果的方块会在客户端线程触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def dropName(self):
        # type: () -> str
        """ 触发剪刀效果的掉落物identifier，包含命名空间及名称 """
        return self.mArgs.get("dropName")

    @property
    def dropCount(self):
        # type: () -> int
        """ 触发剪刀效果的掉落物数量 """
        return self.mArgs.get("dropCount")

    @property
    def playerId(self):
        # type: () -> str
        """ 触发剪刀效果的玩家id """
        return self.mArgs.get("playerId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 玩家触发时的维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancelShears(self):
        # type: () -> bool
        """ 是否取消剪刀效果 """
        return self.mArgs.get("cancelShears")

class ShearsDestoryBlockBeforeServerEvent(object):
    """ [服务端] 触发时机：玩家手持剪刀破坏方块时，有剪刀特殊效果的方块会在服务端线程触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def dropName(self):
        # type: () -> str
        """ 触发剪刀效果的掉落物identifier，包含命名空间及名称 """
        return self.mArgs.get("dropName")

    @property
    def dropCount(self):
        # type: () -> int
        """ 触发剪刀效果的掉落物数量 """
        return self.mArgs.get("dropCount")

    @property
    def playerId(self):
        # type: () -> str
        """ 触发剪刀效果的玩家id """
        return self.mArgs.get("playerId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 玩家触发时的维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancelShears(self):
        # type: () -> bool
        """ 是否取消剪刀效果 """
        return self.mArgs.get("cancelShears")

class StartDestroyBlockClientEvent(object):
    """ [客户端] 玩家开始挖方块时触发。创造模式下不触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def pos(self):
        # type: () -> tuple[float, float, float]
        """ 方块的坐标 """
        return self.mArgs.get("pos")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("auxValue")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可阻止玩家进入挖方块的状态。需要与StartDestroyBlockServerEvent一起修改。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def face(self):
        # type: () -> int
        """ 方块被敲击面,参考Facing枚举 """
        return self.mArgs.get("face")

class StartDestroyBlockServerEvent(object):
    """ [服务端] 玩家开始挖方块时触发。创造模式下不触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def pos(self):
        # type: () -> tuple[float, float, float]
        """ 方块的坐标 """
        return self.mArgs.get("pos")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("auxValue")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可阻止玩家进入挖方块的状态。需要与StartDestroyBlockClientEvent一起修改。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def face(self):
        # type: () -> int
        """ 方块被敲击面,参考Facing枚举 """
        return self.mArgs.get("face")

class StepOffBlockClientEvent(object):
    """ [客户端] 触发时机：实体移动离开一个实心方块时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发的entity的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class StepOffBlockServerEvent(object):
    """ [服务端] 触发时机：实体移动离开一个实心方块时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发的entity的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class StepOnBlockClientEvent(object):
    """ [客户端] 触发时机：实体刚移动至一个新实心方块时触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续原版逻辑 """
        return self.mArgs.get("cancel")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发的entity的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class StepOnBlockServerEvent(object):
    """ [服务端] 触发时机：实体刚移动至一个新实心方块时触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续物理交互事件 """
        return self.mArgs.get("cancel")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发的entity的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")
