# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class ClientJumpButtonPressDownEvent(object):
    """ [客户端] 跳跃按钮按下事件，返回值设置参数只对当次按下事件起作用 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def continueJump(self):
        # type: () -> bool
        """ 设置是否执行跳跃逻辑 """
        return self.mArgs.get("continueJump")

    @continueJump.setter
    def continueJump(self, value):
        self.mArgs["continueJump"] = value

class ClientJumpButtonReleaseEvent(object):
    """ [客户端] 跳跃按钮按下释放事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class GetEntityByCoordEvent(object):
    """ [客户端] 玩家点击屏幕时触发，多个手指点在屏幕上时，只有第一个会触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class GetEntityByCoordReleaseClientEvent(object):
    """ [客户端] 玩家点击屏幕后松开时触发，多个手指点在屏幕上时，只有最后一个手指松开时触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class GyroSensorChangedClientEvent(object):
    """ [客户端] 触发时机：陀螺仪传感器姿态发生变化时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def xDiff(self):
        # type: () -> float
        """ x轴角速度，单位为弧度/s """
        return self.mArgs.get("xDiff")

    @property
    def yDiff(self):
        # type: () -> float
        """ y轴角速度，单位为弧度/s """
        return self.mArgs.get("yDiff")

    @property
    def zDiff(self):
        # type: () -> float
        """ z轴角速度，单位为弧度/s """
        return self.mArgs.get("zDiff")

    @property
    def orientation(self):
        # type: () -> int
        """ 当前屏幕朝向,0竖屏正向 1横屏向左 2竖屏倒置 3横屏向右 """
        return self.mArgs.get("orientation")

    @property
    def timestamp(self):
        # type: () -> float
        """ 触发时间戳,秒 """
        return self.mArgs.get("timestamp")

class HoldBeforeClientEvent(object):
    """ [客户端] 玩家长按屏幕，即将响应到游戏内时触发。仅在移动端或pc的F11模式下触发。pc的非F11模式可以监听RightClickBeforeClientEvent事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截原版的挖方块/使用物品/与实体交互响应 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class LeftClickBeforeClientEvent(object):
    """ [客户端] 玩家按下攻击/摧毁键时触发，例如鼠标左键、新触控攻击键、手柄右扳机键。鼠标左键仅在pc的普通控制模式（即非F11模式）下触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截原版的挖方块或攻击响应 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class LeftClickReleaseClientEvent(object):
    """ [客户端] 玩家松开攻击/摧毁键时触发，例如鼠标左键、新触控攻击键、手柄右扳机键。鼠标左键仅在pc的普通控制模式（即非F11模式）下触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class MouseWheelClientEvent(object):
    """ [客户端] 鼠标滚轮滚动时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def direction(self):
        # type: () -> int
        """ 1为向上滚动，0为向下滚动 """
        return self.mArgs.get("direction")

class OnBackButtonReleaseClientEvent(object):
    """ [客户端] 返回按钮（目前特指安卓系统导航中的返回按钮）松开时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class OnClientPlayerStartMove(object):
    """ [客户端] 移动按钮按下触发事件，在按住一个方向键的同时，去按另外一个方向键，不会触发第二次 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class OnClientPlayerStopMove(object):
    """ [客户端] 移动按钮按下释放时触发事件，同时按下多个方向键，需要释放所有的方向键才会触发事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class OnGamepadControllerLayoutChangeClientEvent(object):
    """ [客户端] 游戏手柄按键映射改变事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def action(self):
        # type: () -> str
        """ 行为 """
        return self.mArgs.get("action")

    @property
    def newKey(self):
        # type: () -> int
        """ 修改后的键码，详见GamepadKeyType枚举 """
        return self.mArgs.get("newKey")

    @newKey.setter
    def newKey(self, value):
        self.mArgs["newKey"] = value

    @property
    def oldKey(self):
        # type: () -> int
        """ 修改前的键码，详见GamepadKeyType枚举 """
        return self.mArgs.get("oldKey")

    @oldKey.setter
    def oldKey(self, value):
        self.mArgs["oldKey"] = value

class OnGamepadKeyPressClientEvent(object):
    """ [客户端] 游戏手柄按键事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def screenName(self):
        # type: () -> str
        """ 当前screenName """
        return self.mArgs.get("screenName")

    @property
    def key(self):
        # type: () -> int
        """ 键码，详见GamepadKeyType枚举 """
        return self.mArgs.get("key")

    @property
    def isDown(self):
        # type: () -> str
        """ 是否按下，按下为1，弹起为0 """
        return self.mArgs.get("isDown")

class OnGamepadStickClientEvent(object):
    """ [客户端] 游戏手柄摇杆事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def key(self):
        # type: () -> int
        """ 键码，详见GamepadKeyType枚举 """
        return self.mArgs.get("key")

    @property
    def x(self):
        # type: () -> float
        """ 摇杆水平方向的值，从左到右取值为 -1.0 ~ 1.0 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> float
        """ 摇杆竖直方向的值，从下到上取值为 -1.0 ~ 1.0 """
        return self.mArgs.get("y")

class OnGamepadTriggerClientEvent(object):
    """ [客户端] 游戏手柄扳机事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def key(self):
        # type: () -> int
        """ 键码，详见GamepadKeyType枚举 """
        return self.mArgs.get("key")

    @property
    def magnitude(self):
        # type: () -> float
        """ 扣动扳机的力度，取值为 0 ~ 1.0 """
        return self.mArgs.get("magnitude")

class OnKeyPressInGame(object):
    """ [客户端] 按键按下或按键释放时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def screenName(self):
        # type: () -> str
        """ 当前screenName """
        return self.mArgs.get("screenName")

    @property
    def key(self):
        # type: () -> str
        """ 键码（注：这里的int型被转成了str型，比如"1"对应的就是枚举值文档中的1），详见KeyBoardType枚举 """
        return self.mArgs.get("key")

    @property
    def isDown(self):
        # type: () -> str
        """ 是否按下，按下为1，弹起为0 """
        return self.mArgs.get("isDown")

class OnKeyboardControllerLayoutChangeClientEvent(object):
    """ [客户端] 键盘按键映射改变事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def action(self):
        # type: () -> str
        """ 行为 """
        return self.mArgs.get("action")

    @property
    def newKey(self):
        # type: () -> int
        """ 修改后的键码，详见KeyBoardType枚举 """
        return self.mArgs.get("newKey")

    @newKey.setter
    def newKey(self, value):
        self.mArgs["newKey"] = value

    @property
    def oldKey(self):
        # type: () -> int
        """ 修改前的键码，详见KeyBoardType枚举 """
        return self.mArgs.get("oldKey")

    @oldKey.setter
    def oldKey(self, value):
        self.mArgs["oldKey"] = value

class OnMouseMiddleDownClientEvent(object):
    """ [客户端] 鼠标按下中键时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def isDown(self):
        # type: () -> int
        """ 1为按下，0为弹起 """
        return self.mArgs.get("isDown")

    @property
    def mousePositionX(self):
        # type: () -> float
        """ 按下时的x坐标 """
        return self.mArgs.get("mousePositionX")

    @property
    def mousePositionY(self):
        # type: () -> float
        """ 按下时的y坐标 """
        return self.mArgs.get("mousePositionY")

class RightClickBeforeClientEvent(object):
    """ [客户端] 玩家按下使用物品/放置方块键时触发，例如鼠标右键、新触控交互键、手柄左扳机键 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截原版的物品使用/实体交互响应 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class RightClickReleaseClientEvent(object):
    """ [客户端] 玩家松开使用物品/放置方块键时触发，例如鼠标右键、新触控交互键、手柄左扳机键 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class TapBeforeClientEvent(object):
    """ [客户端] 玩家点击屏幕并松手，即将响应到游戏内时触发。仅在移动端或pc的F11模式下触发。pc的非F11模式可以监听LeftClickBeforeClientEvent事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可拦截原版的攻击或放置响应 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class TapOrHoldReleaseClientEvent(object):
    """ [客户端] 玩家点击屏幕后松手时触发。仅在移动端或pc的F11模式下触发。pc的非F11模式可以使用LeftClickReleaseClientEvent与RightClickReleaseClientEvent事件监听鼠标松开 """
    def __init__(self, args=None):
        self.mArgs = args or dict()
