# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class ActorHurtServerEvent(object):
    """ [服务端] 触发时机：生物（包括玩家）受伤时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 生物Id """
        return self.mArgs.get("entityId")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

    @property
    def damage(self):
        # type: () -> float
        """ 伤害值（被伤害吸收后的值），不可修改 """
        return self.mArgs.get("damage")

    @property
    def absorbedDamage(self):
        # type: () -> int
        """ 被伤害吸收效果吸收的伤害值 """
        return self.mArgs.get("absorbedDamage")

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

class ActuallyHurtServerEvent(object):
    """ [服务端] 实体实际受到伤害时触发，相比于DamageEvent，该伤害为经过护甲及buff计算后，实际的扣血量 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def srcId(self):
        # type: () -> str
        """ 伤害源id """
        return self.mArgs.get("srcId")

    @property
    def projectileId(self):
        # type: () -> str
        """ 投射物id """
        return self.mArgs.get("projectileId")

    @property
    def entityId(self):
        # type: () -> str
        """ 被伤害id """
        return self.mArgs.get("entityId")

    @property
    def damage(self):
        # type: () -> float
        """ 伤害值（被伤害吸收后的值），允许修改，设置为0则此次造成的伤害为0，若设置数值和原来一样则视为没有修改 """
        return self.mArgs.get("damage")

    @damage.setter
    def damage(self, value):
        self.mArgs["damage"] = value

    @property
    def invulnerableTime(self):
        # type: () -> int
        """ 实体受击后，剩余的无懈可击帧数，在无懈可击时间内，damage和damage_f为超过上次伤害的部分 """
        return self.mArgs.get("invulnerableTime")

    @property
    def lastHurt(self):
        # type: () -> float
        """ 实体上次受到的伤害 """
        return self.mArgs.get("lastHurt")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

class AddEffectServerEvent(object):
    """ [服务端] 触发时机：实体获得状态效果时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def effectName(self):
        # type: () -> str
        """ 实体获得状态效果的名字 """
        return self.mArgs.get("effectName")

    @property
    def effectDuration(self):
        # type: () -> int
        """ 状态效果的持续时间，单位秒 """
        return self.mArgs.get("effectDuration")

    @property
    def effectAmplifier(self):
        # type: () -> int
        """ 状态效果的放大倍数 """
        return self.mArgs.get("effectAmplifier")

    @property
    def damage(self):
        # type: () -> float
        """ 状态造成的伤害值（真实扣除生命值的量）。只有持续时间为0时有用 """
        return self.mArgs.get("damage")

class ApproachEntityClientEvent(object):
    """ [客户端] 玩家靠近生物时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def entityId(self):
        # type: () -> str
        """ 靠近的生物实体id """
        return self.mArgs.get("entityId")

class ChangeSwimStateServerEvent(object):
    """ [服务端] 触发时机：实体开始或者结束游泳时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def formState(self):
        # type: () -> bool
        """ 事件触发前，实体是否在游泳状态 """
        return self.mArgs.get("formState")

    @property
    def toState(self):
        # type: () -> bool
        """ 事件触发后，实体是否在游泳状态 """
        return self.mArgs.get("toState")

class DamageEvent(object):
    """ [服务端] 实体受到伤害时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def srcId(self):
        # type: () -> str
        """ 伤害源id """
        return self.mArgs.get("srcId")

    @property
    def projectileId(self):
        # type: () -> str
        """ 投射物id """
        return self.mArgs.get("projectileId")

    @property
    def entityId(self):
        # type: () -> str
        """ 被伤害id """
        return self.mArgs.get("entityId")

    @property
    def damage(self):
        # type: () -> float
        """ 伤害值（被伤害吸收前的值），允许修改，设置为0则此次造成的伤害为0 """
        return self.mArgs.get("damage")

    @damage.setter
    def damage(self, value):
        self.mArgs["damage"] = value

    @property
    def absorption(self):
        # type: () -> int
        """ 受到伤害时，扣除黄心前，实体拥有的黄心血量（见AttrType枚举的ABSORPTION） """
        return self.mArgs.get("absorption")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

    @property
    def knock(self):
        # type: () -> bool
        """ 是否击退被攻击者，允许修改，设置该值为False则不产生击退 """
        return self.mArgs.get("knock")

    @knock.setter
    def knock(self, value):
        self.mArgs["knock"] = value

    @property
    def ignite(self):
        # type: () -> bool
        """ 是否点燃被伤害者，允许修改，设置该值为True产生点燃效果 """
        return self.mArgs.get("ignite")

    @ignite.setter
    def ignite(self, value):
        self.mArgs["ignite"] = value

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

class EntityChangeDimensionServerEvent(object):
    """ [服务端] 实体维度改变时服务端抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 维度改变前的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 维度改变后的维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def fromX(self):
        # type: () -> float
        """ 改变前的位置x """
        return self.mArgs.get("fromX")

    @property
    def fromY(self):
        # type: () -> float
        """ 改变前的位置Y """
        return self.mArgs.get("fromY")

    @property
    def fromZ(self):
        # type: () -> float
        """ 改变前的位置Z """
        return self.mArgs.get("fromZ")

    @property
    def toX(self):
        # type: () -> float
        """ 改变后的位置x """
        return self.mArgs.get("toX")

    @property
    def toY(self):
        # type: () -> float
        """ 改变后的位置Y """
        return self.mArgs.get("toY")

    @property
    def toZ(self):
        # type: () -> float
        """ 改变后的位置Z """
        return self.mArgs.get("toZ")

class EntityDefinitionsEventServerEvent(object):
    """ [服务端] 触发时机：生物定义json文件中设置的event触发时同时触发。生物行为变更事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 生物id """
        return self.mArgs.get("entityId")

    @property
    def eventName(self):
        # type: () -> str
        """ 触发的事件名称 """
        return self.mArgs.get("eventName")

class EntityDieLoottableAfterServerEvent(object):
    """ [服务端] 触发时机：生物死亡掉落物品之后 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dieEntityId(self):
        # type: () -> str
        """ 死亡实体的entityId """
        return self.mArgs.get("dieEntityId")

    @property
    def attacker(self):
        # type: () -> str
        """ 伤害来源的entityId """
        return self.mArgs.get("attacker")

    @property
    def itemList(self):
        # type: () -> list[dict]
        """ 掉落物品列表，每个元素为一个itemDict，格式可参考物品信息字典 """
        return self.mArgs.get("itemList")

    @property
    def itemEntityIdList(self):
        # type: () -> list[str]
        """ 掉落物品entityId列表 """
        return self.mArgs.get("itemEntityIdList")

class EntityDieLoottableServerEvent(object):
    """ [服务端] 触发时机：生物死亡掉落物品时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dieEntityId(self):
        # type: () -> str
        """ 死亡实体的entityId """
        return self.mArgs.get("dieEntityId")

    @property
    def attacker(self):
        # type: () -> str
        """ 伤害来源的entityId """
        return self.mArgs.get("attacker")

    @property
    def itemList(self):
        # type: () -> list[dict]
        """ 掉落物品列表，每个元素为一个itemDict，格式可参考物品信息字典 """
        return self.mArgs.get("itemList")

    @property
    def dirty(self):
        # type: () -> bool
        """ 默认为False，如果需要修改掉落列表需将该值设为True """
        return self.mArgs.get("dirty")

    @dirty.setter
    def dirty(self, value):
        self.mArgs["dirty"] = value

class EntityDroppedItemServerEvent(object):
    """ [服务端] 触发时机：生物扔出物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 生物Id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 扔出的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def itemEntityId(self):
        # type: () -> str
        """ 物品实体Id """
        return self.mArgs.get("itemEntityId")

class EntityEffectDamageServerEvent(object):
    """ [服务端] 生物受到状态伤害/回复事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def damage(self):
        # type: () -> float
        """ 伤害值（伤害吸收后实际扣血量），负数表示生命回复量 """
        return self.mArgs.get("damage")

    @property
    def attributeBuffType(self):
        # type: () -> int
        """ 状态类型，参考AttributeBuffType """
        return self.mArgs.get("attributeBuffType")

    @property
    def duration(self):
        # type: () -> float
        """ 状态持续时间，单位秒（s） """
        return self.mArgs.get("duration")

    @property
    def lifeTimer(self):
        # type: () -> float
        """ 状态生命时间，单位秒（s） """
        return self.mArgs.get("lifeTimer")

    @property
    def isInstantaneous(self):
        # type: () -> bool
        """ 是否为立即生效状态 """
        return self.mArgs.get("isInstantaneous")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

class EntityLoadScriptEvent(object):
    """ [服务端] 数据库加载实体自定义数据时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def args(self):
        # type: () -> list
        """ 该事件的参数为长度为2的list，而非dict，其中list的第一个元素为实体id """
        return self.mArgs.get("args")

class EntityModelChangedClientEvent(object):
    """ [客户端] 触发时机：实体模型切换时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def newModel(self):
        # type: () -> str
        """ 新的模型名字 """
        return self.mArgs.get("newModel")

    @property
    def oldModel(self):
        # type: () -> str
        """ 原来的模型名字 """
        return self.mArgs.get("oldModel")

class EntityMotionStartServerEvent(object):
    """ [服务端] 实体运动器开始事件。实体（包含玩家）添加运动器后，运动器开始运行时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def motionId(self):
        # type: () -> int
        """ 运动器id """
        return self.mArgs.get("motionId")

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

class EntityMotionStopServerEvent(object):
    """ [服务端] 实体运动器停止事件。实体（包含玩家）添加运动器并开始运行后，运动器自动停止时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def motionId(self):
        # type: () -> int
        """ 运动器id """
        return self.mArgs.get("motionId")

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def remove(self):
        # type: () -> bool
        """ 是否移除该运动器，设置为False则保留，默认为True，即运动器停止后自动移除，该参数设置只对非玩家实体有效 """
        return self.mArgs.get("remove")

    @remove.setter
    def remove(self, value):
        self.mArgs["remove"] = value

class EntityPickupItemServerEvent(object):
    """ [服务端] 有minecraft:behavior.pickup_items行为的生物拾取物品时触发该事件，例如村民拾取面包、猪灵拾取金锭 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 生物Id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 拾取的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def secondaryActor(self):
        # type: () -> str
        """ 物品给予者id（一般是玩家），如果不存在给予者的话，这里为空字符串 """
        return self.mArgs.get("secondaryActor")

class EntityStartRidingEvent(object):
    """ [服务端] 当实体骑乘上另一个实体时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 乘骑者实体id """
        return self.mArgs.get("id")

    @property
    def rideId(self):
        # type: () -> str
        """ 被乘骑者实体id """
        return self.mArgs.get("rideId")

class EntityStopRidingEvent(object):
    """ [双端] 触发时机：当实体停止骑乘时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

    @property
    def rideId(self):
        # type: () -> str
        """ 坐骑id """
        return self.mArgs.get("rideId")

    @property
    def exitFromRider(self):
        # type: () -> bool
        """ 是否下坐骑 """
        return self.mArgs.get("exitFromRider")

    @property
    def entityIsBeingDestroyed(self):
        # type: () -> bool
        """ 坐骑是否将要销毁 """
        return self.mArgs.get("entityIsBeingDestroyed")

    @property
    def switchingRides(self):
        # type: () -> bool
        """ 是否换乘坐骑 """
        return self.mArgs.get("switchingRides")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可以取消（需要与客户端事件一同取消） """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class EntityTickServerEvent(object):
    """ [服务端] 实体tick时触发。该事件为20帧每秒。需要使用AddEntityTickEventWhiteList添加触发该事件的实体类型白名单。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def identifier(self):
        # type: () -> str
        """ 实体identifier """
        return self.mArgs.get("identifier")

class HealthChangeBeforeServerEvent(object):
    """ [服务端] 生物生命值或最大生命值发生变化之前触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def _from(self):
        # type: () -> float
        """ 变化前的生命值 """
        return self.mArgs.get("from")

    @property
    def to(self):
        # type: () -> float
        """ 将要变化到的生命值，cancel设置为True时可以取消该变化，但是此参数不变 """
        return self.mArgs.get("to")

    @to.setter
    def to(self, value):
        self.mArgs["to"] = value

    @property
    def byScript(self):
        # type: () -> bool
        """ 是否通过SetAttrValue或SetAttrMaxValue调用产生的变化 """
        return self.mArgs.get("byScript")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该变化 """
        return self.mArgs.get("cancel")

class HealthChangeClientEvent(object):
    """ [客户端] 生物生命值发生变化时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def _from(self):
        # type: () -> float
        """ 变化前的生命值 """
        return self.mArgs.get("from")

    @property
    def to(self):
        # type: () -> float
        """ 变化后的生命值 """
        return self.mArgs.get("to")

class HealthChangeServerEvent(object):
    """ [服务端] 生物生命值发生变化时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def _from(self):
        # type: () -> float
        """ 变化前的生命值 """
        return self.mArgs.get("from")

    @property
    def to(self):
        # type: () -> float
        """ 变化后的生命值 """
        return self.mArgs.get("to")

    @property
    def byScript(self):
        # type: () -> bool
        """ 是否通过SetAttrValue或SetAttrMaxValue调用产生的变化 """
        return self.mArgs.get("byScript")

class LeaveEntityClientEvent(object):
    """ [客户端] 玩家远离生物时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def entityId(self):
        # type: () -> str
        """ 远离的生物实体id """
        return self.mArgs.get("entityId")

class MobDieEvent(object):
    """ [服务端] 实体死亡时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

    @property
    def attacker(self):
        # type: () -> str
        """ 伤害来源id """
        return self.mArgs.get("attacker")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

class MobGriefingBlockServerEvent(object):
    """ [服务端] 环境生物改变方块时触发，触发的时机与mobgriefing游戏规则影响的行为相同 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续物理交互事件 """
        return self.mArgs.get("cancel")

    @property
    def blockX(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("blockZ")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发的entity的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class OnFireHurtEvent(object):
    """ [服务端] 生物受到火焰伤害时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def victim(self):
        # type: () -> str
        """ 受伤实体id """
        return self.mArgs.get("victim")

    @property
    def src(self):
        # type: () -> str
        """ 火焰创建者id """
        return self.mArgs.get("src")

    @property
    def fireTime(self):
        # type: () -> float
        """ 着火时间，单位秒, 不支持修改 """
        return self.mArgs.get("fireTime")

    @fireTime.setter
    def fireTime(self, value):
        self.mArgs["fireTime"] = value

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消此处火焰伤害 """
        return self.mArgs.get("cancel")

    @property
    def cancelIgnite(self):
        # type: () -> bool
        """ 是否取消点燃效果 """
        return self.mArgs.get("cancelIgnite")

class OnGroundClientEvent(object):
    """ [客户端] 实体着地事件。玩家，沙子，铁砧，掉落的物品，点燃的TNT掉落地面时触发，其余实体着地不触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class OnGroundServerEvent(object):
    """ [服务端] 实体着地事件。实体，掉落的物品，点燃的TNT掉落地面时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class OnKnockBackServerEvent(object):
    """ [服务端] 实体被击退时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class OnMobHitBlockServerEvent(object):
    """ [服务端] 触发时机：通过OpenMobHitBlockDetection打开方块碰撞检测后，当生物（不包括玩家）碰撞到方块时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 碰撞到方块的生物Id """
        return self.mArgs.get("entityId")

    @property
    def posX(self):
        # type: () -> int
        """ 碰撞方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 碰撞方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 碰撞方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockId(self):
        # type: () -> str
        """ 碰撞方块的identifier """
        return self.mArgs.get("blockId")

    @property
    def auxValue(self):
        # type: () -> int
        """ 碰撞方块的附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class OnMobHitMobClientEvent(object):
    """ [客户端] 触发时机：通过OpenPlayerHitMobDetection打开生物碰撞检测后，当生物间（包含玩家）碰撞时触发该事件。注：客户端和服务端分别作碰撞检测，可能两个事件返回的略有差异。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def mobId(self):
        # type: () -> str
        """ 当前生物的id """
        return self.mArgs.get("mobId")

    @property
    def hittedMobList(self):
        # type: () -> list[str]
        """ 当前生物碰撞到的其他所有生物id的list """
        return self.mArgs.get("hittedMobList")

class OnMobHitMobServerEvent(object):
    """ [服务端] 触发时机：通过OpenPlayerHitMobDetection打开生物碰撞检测后，当生物间（包含玩家）碰撞时触发该事件。注：客户端和服务端分别作碰撞检测，可能两个事件返回的略有差异。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def mobId(self):
        # type: () -> str
        """ 当前生物的id """
        return self.mArgs.get("mobId")

    @property
    def hittedMobList(self):
        # type: () -> list[str]
        """ 当前生物碰撞到的其他所有生物id的list """
        return self.mArgs.get("hittedMobList")

class ProjectileCritHitEvent(object):
    """ [服务端] 触发时机：当抛射物与头部碰撞时触发该事件。注：需调用OpenPlayerCritBox开启玩家爆头后才能触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 抛射物id """
        return self.mArgs.get("id")

    @property
    def targetId(self):
        # type: () -> str
        """ 碰撞目标id """
        return self.mArgs.get("targetId")

class ProjectileDoHitEffectEvent(object):
    """ [服务端] 触发时机：当抛射物碰撞时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 抛射物id """
        return self.mArgs.get("id")

    @property
    def hitTargetType(self):
        # type: () -> str
        """ 碰撞目标类型,'ENTITY'或是'BLOCK' """
        return self.mArgs.get("hitTargetType")

    @property
    def targetId(self):
        # type: () -> str
        """ 碰撞目标id """
        return self.mArgs.get("targetId")

    @property
    def hitFace(self):
        # type: () -> int
        """ 撞击在方块上的面id，参考Facing枚举 """
        return self.mArgs.get("hitFace")

    @property
    def x(self):
        # type: () -> float
        """ 碰撞x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> float
        """ 碰撞y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> float
        """ 碰撞z坐标 """
        return self.mArgs.get("z")

    @property
    def blockPosX(self):
        # type: () -> int
        """ 碰撞是方块时，方块x坐标 """
        return self.mArgs.get("blockPosX")

    @property
    def blockPosY(self):
        # type: () -> int
        """ 碰撞是方块时，方块y坐标 """
        return self.mArgs.get("blockPosY")

    @property
    def blockPosZ(self):
        # type: () -> int
        """ 碰撞是方块时，方块z坐标 """
        return self.mArgs.get("blockPosZ")

    @property
    def srcId(self):
        # type: () -> str
        """ 创建者id """
        return self.mArgs.get("srcId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消这个碰撞事件，若取消可以设置为True """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class RefreshEffectServerEvent(object):
    """ [服务端] 触发时机：实体身上状态效果更新时触发，更新条件1、新增状态等级较高，更新状态等级及时间；2、新增状态等级不变，时间较长，更新状态持续时间 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def effectName(self):
        # type: () -> str
        """ 更新状态效果的名字 """
        return self.mArgs.get("effectName")

    @property
    def effectDuration(self):
        # type: () -> int
        """ 更新后状态效果剩余持续时间，单位秒 """
        return self.mArgs.get("effectDuration")

    @property
    def effectAmplifier(self):
        # type: () -> int
        """ 更新后的状态效果放大倍数 """
        return self.mArgs.get("effectAmplifier")

    @property
    def damage(self):
        # type: () -> float
        """ 状态造成的伤害值，如药水 """
        return self.mArgs.get("damage")

class RemoveEffectServerEvent(object):
    """ [服务端] 触发时机：实体身上状态效果被移除时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def effectName(self):
        # type: () -> str
        """ 被移除状态效果的名字 """
        return self.mArgs.get("effectName")

    @property
    def effectDuration(self):
        # type: () -> int
        """ 被移除状态效果的剩余持续时间，单位秒 """
        return self.mArgs.get("effectDuration")

    @property
    def effectAmplifier(self):
        # type: () -> int
        """ 被移除状态效果的放大倍数 """
        return self.mArgs.get("effectAmplifier")

class SpawnProjectileServerEvent(object):
    """ [服务端] 触发时机：抛射物生成时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def projectileId(self):
        # type: () -> str
        """ 抛射物的实体id """
        return self.mArgs.get("projectileId")

    @property
    def projectileIdentifier(self):
        # type: () -> str
        """ 抛射物的identifier """
        return self.mArgs.get("projectileIdentifier")

    @property
    def spawnerId(self):
        # type: () -> str
        """ 发射者的实体id，没有发射者时为-1 """
        return self.mArgs.get("spawnerId")

class StartRidingClientEvent(object):
    """ [客户端] 触发时机：一个实体即将骑乘另外一个实体 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def actorId(self):
        # type: () -> str
        """ 骑乘者的唯一ID """
        return self.mArgs.get("actorId")

    @property
    def victimId(self):
        # type: () -> str
        """ 被骑乘实体的唯一ID """
        return self.mArgs.get("victimId")

class StartRidingServerEvent(object):
    """ [服务端] 触发时机：一个实体即将骑乘另外一个实体 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续的实体交互事件 """
        return self.mArgs.get("cancel")

    @property
    def actorId(self):
        # type: () -> str
        """ 骑乘者的唯一ID """
        return self.mArgs.get("actorId")

    @property
    def victimId(self):
        # type: () -> str
        """ 被骑乘实体的唯一ID """
        return self.mArgs.get("victimId")

class WillAddEffectServerEvent(object):
    """ [服务端] 触发时机：实体即将获得状态效果前 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def effectName(self):
        # type: () -> str
        """ 实体获得状态效果的名字 """
        return self.mArgs.get("effectName")

    @property
    def effectDuration(self):
        # type: () -> int
        """ 状态效果的持续时间，单位秒 """
        return self.mArgs.get("effectDuration")

    @property
    def effectAmplifier(self):
        # type: () -> int
        """ 状态效果的放大倍数 """
        return self.mArgs.get("effectAmplifier")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可以取消 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def damage(self):
        # type: () -> float
        """ 状态将会造成的伤害值，如药水；需要注意，该值不一定是最终的伤害值，例如被伤害吸收效果扣除。只有持续时间为0时有用 """
        return self.mArgs.get("damage")

class WillTeleportToServerEvent(object):
    """ [服务端] 实体即将传送或切换维度 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否允许触发，默认为False，若设为True，可阻止触发后续的传送 """
        return self.mArgs.get("cancel")

    @property
    def entityId(self):
        # type: () -> str
        """ 实体的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 传送前所在的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 传送后的目标维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def fromX(self):
        # type: () -> int
        """ 传送前所在的x坐标 """
        return self.mArgs.get("fromX")

    @property
    def fromY(self):
        # type: () -> int
        """ 传送前所在的y坐标 """
        return self.mArgs.get("fromY")

    @property
    def fromZ(self):
        # type: () -> int
        """ 传送前所在的z坐标 """
        return self.mArgs.get("fromZ")

    @property
    def toX(self):
        # type: () -> int
        """ 传送目标地点的x坐标 """
        return self.mArgs.get("toX")

    @property
    def toY(self):
        # type: () -> int
        """ 传送目标地点的y坐标 """
        return self.mArgs.get("toY")

    @property
    def toZ(self):
        # type: () -> int
        """ 传送目标地点的z坐标 """
        return self.mArgs.get("toZ")

    @property
    def cause(self):
        # type: () -> str
        """ 传送理由，详情见MinecraftEnum.EntityTeleportCause """
        return self.mArgs.get("cause")
