# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class ActorAcquiredItemClientEvent(object):
    """ [客户端] 触发时机：玩家获得物品时客户端抛出的事件（有些获取物品方式只会触发客户端事件，有些获取物品方式只会触发服务端事件，在使用时注意一点。） """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def actor(self):
        # type: () -> str
        """ 获得物品玩家实体id """
        return self.mArgs.get("actor")

    @property
    def secondaryActor(self):
        # type: () -> str
        """ 物品给予者玩家实体id，如果不存在给予者的话，这里为空字符串 """
        return self.mArgs.get("secondaryActor")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 获取到的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def acquireMethod(self):
        # type: () -> int
        """ 获得物品的方法，详见ItemAcquisitionMethod """
        return self.mArgs.get("acquireMethod")

class ActorAcquiredItemServerEvent(object):
    """ [服务端] 触发时机：玩家获得物品时服务端抛出的事件（有些获取物品方式只会触发客户端事件，有些获取物品方式只会触发服务端事件，在使用时注意一点。） """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def actor(self):
        # type: () -> str
        """ 获得物品玩家实体id """
        return self.mArgs.get("actor")

    @property
    def secondaryActor(self):
        # type: () -> str
        """ 物品给予者玩家实体id，如果不存在给予者的话，这里为空字符串 """
        return self.mArgs.get("secondaryActor")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 获得的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def acquireMethod(self):
        # type: () -> int
        """ 获得物品的方法，详见ItemAcquisitionMethod枚举 """
        return self.mArgs.get("acquireMethod")

class ActorUseItemClientEvent(object):
    """ [客户端] 触发时机：玩家使用物品时客户端抛出的事件（比较特殊不走该事件的例子：1）染料对有水的炼药锅使用；2）盔甲架装备盔甲）;3)喝牛奶 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def useMethod(self):
        # type: () -> int
        """ 使用物品的方法，详见ItemUseMethodEnum枚举 """
        return self.mArgs.get("useMethod")

class ActorUseItemServerEvent(object):
    """ [服务端] 触发时机：玩家使用物品生效之前服务端抛出的事件（比较特殊不走该事件的例子：1）染料对有水的炼药锅使用；2）盔甲架装备盔甲） """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def useMethod(self):
        # type: () -> int
        """ 使用物品的方法，详见ItemUseMethodEnum枚举 """
        return self.mArgs.get("useMethod")

class AnvilCreateResultItemAfterClientEvent(object):
    """ [客户端] 玩家点击铁砧合成得到的物品时抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemShowName(self):
        # type: () -> str
        """ 合成后的物品显示名称 """
        return self.mArgs.get("itemShowName")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 合成后的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 合成前的物品的物品信息字典（铁砧内第一个物品） """
        return self.mArgs.get("oldItemDict")

    @property
    def materialItemDict(self):
        # type: () -> dict
        """ 合成所使用材料的物品信息字典（铁砧内第二个物品） """
        return self.mArgs.get("materialItemDict")

class ClientItemTryUseEvent(object):
    """ [客户端] 玩家点击右键尝试使用物品时客户端抛出的事件，可以通过设置cancel为True取消使用物品。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 取消使用物品 """
        return self.mArgs.get("cancel")

class ClientItemUseOnEvent(object):
    """ [客户端] 玩家在对方块使用物品时客户端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def x(self):
        # type: () -> int
        """ 方块 x 坐标值 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块 y 坐标值 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块 z 坐标值 """
        return self.mArgs.get("z")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier """
        return self.mArgs.get("blockName")

    @property
    def blockAuxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("blockAuxValue")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

    @property
    def ret(self):
        # type: () -> bool
        """ 设为True可取消物品的使用 """
        return self.mArgs.get("ret")

class ClientShapedRecipeTriggeredEvent(object):
    """ [客户端] 玩家合成物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def recipeId(self):
        # type: () -> str
        """ 配方id，对应配方json文件中的identifier字段 """
        return self.mArgs.get("recipeId")

class ContainerItemChangedServerEvent(object):
    """ [服务端] 容器物品变化事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def pos(self):
        # type: () -> tuple[int, int, int] | None
        """ 容器坐标 """
        return self.mArgs.get("pos")

    @property
    def containerType(self):
        # type: () -> int
        """ 容器类型，类型含义见：容器类型枚举 """
        return self.mArgs.get("containerType")

    @property
    def slot(self):
        # type: () -> int
        """ 容器槽位 """
        return self.mArgs.get("slot")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 旧物品，格式参考物品信息字典 """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict
        """ 新物品，格式参考物品信息字典 """
        return self.mArgs.get("newItemDict")

class CraftItemOutputChangeServerEvent(object):
    """ [服务端] 玩家从容器拿出生成物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 生成的物品，格式参考物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def screenContainerType(self):
        # type: () -> int
        """ 当前界面类型,类型含义见：容器类型枚举 """
        return self.mArgs.get("screenContainerType")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消生成物品 """
        return self.mArgs.get("cancel")

class CraftUpdateResultItemClientEvent(object):
    """ [客户端] 玩家工作台界面更新显示可合成物品时抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 合成后的物品的[物品信息字典] """
        return self.mArgs.get("itemDict")

class FurnaceBurnFinishedServerEvent(object):
    """ [服务端] 服务端熔炉烧制触发事件。熔炉, 高炉，烟熏炉烧出物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def posX(self):
        # type: () -> float
        """ 位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 位置z """
        return self.mArgs.get("posZ")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 物品的物品信息字典，当新物品为空时，此项属性为None """
        return self.mArgs.get("itemDict")

class GrindStoneRemovedEnchantClientEvent(object):
    """ [客户端] 玩家点击砂轮合成得到的物品时抛出的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 合成前的物品物品信息字典（砂轮内第一个物品） """
        return self.mArgs.get("oldItemDict")

    @property
    def additionalItemDict(self):
        # type: () -> dict
        """ 作为合成材料的物品物品信息字典（砂轮内第二个物品） """
        return self.mArgs.get("additionalItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict
        """ 合成后的物品物品信息字典 """
        return self.mArgs.get("newItemDict")

    @property
    def exp(self):
        # type: () -> int
        """ 本次合成返还的经验 """
        return self.mArgs.get("exp")

class InventoryItemChangedClientEvent(object):
    """ [客户端] 玩家背包物品变化时客户端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def slot(self):
        # type: () -> int
        """ 背包槽位 """
        return self.mArgs.get("slot")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 变化前槽位中的物品，格式参考物品信息字典 """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict
        """ 变化后槽位中的物品，格式参考物品信息字典 """
        return self.mArgs.get("newItemDict")

class InventoryItemChangedServerEvent(object):
    """ [服务端] 玩家背包物品变化时服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def slot(self):
        # type: () -> int
        """ 背包槽位 """
        return self.mArgs.get("slot")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 变化前槽位中的物品，格式参考物品信息字典 """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict
        """ 变化后槽位中的物品，格式参考物品信息字典 """
        return self.mArgs.get("newItemDict")

class ItemDurabilityChangedServerEvent(object):
    """ [服务端] 物品耐久度变化事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 物品拥有者的实体id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def durabilityBefore(self):
        # type: () -> int
        """ 变化前耐久度 """
        return self.mArgs.get("durabilityBefore")

    @property
    def durability(self):
        # type: () -> int
        """ 变化后耐久度,支持修改。但是请注意修改范围，支持范围为[-32768,32767) """
        return self.mArgs.get("durability")

    @durability.setter
    def durability(self, value):
        self.mArgs["durability"] = value

    @property
    def canChange(self):
        # type: () -> bool
        """ 是否支持修改，为true时支持通过durability修改，为false时不支持 """
        return self.mArgs.get("canChange")

    @canChange.setter
    def canChange(self, value):
        self.mArgs["canChange"] = value

class ItemPullOutCustomContainerServerEvent(object):
    """ [服务端] 漏出物品到漏斗时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 漏斗漏出物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 漏出物品的容器名称，目前仅支持netease_container """
        return self.mArgs.get("collectionName")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 漏出物品的容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次漏出物品的操作 """
        return self.mArgs.get("cancel")

class ItemPushInCustomContainerServerEvent(object):
    """ [服务端] 漏斗漏入物品时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 漏斗漏入物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 目标容器名称，目前仅支持netease_container """
        return self.mArgs.get("collectionName")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 目标容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次漏入物品的操作 """
        return self.mArgs.get("cancel")

class ItemReleaseUsingClientEvent(object):
    """ [客户端] 触发时机：释放正在使用的物品 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def durationLeft(self):
        # type: () -> float
        """ 蓄力剩余时间(当物品缺少"minecraft:maxduration"组件时,蓄力剩余时间为负数) """
        return self.mArgs.get("durationLeft")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def maxUseDuration(self):
        # type: () -> int
        """ 最大蓄力时长 """
        return self.mArgs.get("maxUseDuration")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可以取消，需要同时取消服务端事件ItemReleaseUsingServerEvent """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class ItemReleaseUsingServerEvent(object):
    """ [服务端] 触发时机：释放正在使用的物品时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def durationLeft(self):
        # type: () -> float
        """ 蓄力剩余时间(当物品缺少"minecraft:maxduration"组件时,蓄力剩余时间为负数) """
        return self.mArgs.get("durationLeft")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def maxUseDuration(self):
        # type: () -> int
        """ 最大蓄力时长 """
        return self.mArgs.get("maxUseDuration")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可以取消，需要同时取消客户端事件ItemReleaseUsingClientEvent """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def changeItem(self):
        # type: () -> bool
        """ 如果要在该事件的回调中修改当前使用槽位的物品，需设置这个参数为True，否则将修改物品失败，例如修改耐久度或者替换成新物品 """
        return self.mArgs.get("changeItem")

    @changeItem.setter
    def changeItem(self, value):
        self.mArgs["changeItem"] = value

class ItemUseAfterServerEvent(object):
    """ [服务端] 玩家在使用物品之后服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

class ItemUseOnAfterServerEvent(object):
    """ [服务端] 玩家在对方块使用物品之后服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def x(self):
        # type: () -> int
        """ 方块 x 坐标值 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块 y 坐标值 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块 z 坐标值 """
        return self.mArgs.get("z")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier """
        return self.mArgs.get("blockName")

    @property
    def blockAuxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("blockAuxValue")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class OnCarriedNewItemChangedClientEvent(object):
    """ [客户端] 手持物品发生变化时，触发该事件；数量改变不会通知 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 切换后物品的物品信息字典 """
        return self.mArgs.get("itemDict")

class OnCarriedNewItemChangedServerEvent(object):
    """ [服务端] 触发时机：玩家切换主手物品时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldItemDict(self):
        # type: () -> dict | None
        """ 旧物品的物品信息字典，当旧物品为空时，此项属性为None """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict | None
        """ 新物品的物品信息字典，当新物品为空时，此项属性为None """
        return self.mArgs.get("newItemDict")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家 entityId """
        return self.mArgs.get("playerId")

class OnItemPutInEnchantingModelServerEvent(object):
    """ [服务端] 触发时机：玩家将可附魔物品放到附魔台上时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id，参数类型为str """
        return self.mArgs.get("playerId")

    @property
    def slotType(self):
        # type: () -> int
        """ 玩家放入物品的EnchantSlotType """
        return self.mArgs.get("slotType")

    @property
    def options(self):
        # type: () -> list
        """ 附魔台选项 """
        return self.mArgs.get("options")

    @property
    def change(self):
        # type: () -> bool
        """ 传入True时，附魔台选项会被新传入的options覆盖 """
        return self.mArgs.get("change")

class OnNewArmorExchangeServerEvent(object):
    """ [服务端] 触发时机：玩家切换盔甲时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def slot(self):
        # type: () -> int
        """ 槽位id """
        return self.mArgs.get("slot")

    @property
    def oldArmorDict(self):
        # type: () -> dict | None
        """ 旧装备的物品信息字典，当旧物品为空时，此项属性为None """
        return self.mArgs.get("oldArmorDict")

    @property
    def newArmorDict(self):
        # type: () -> dict | None
        """ 新装备的物品信息字典，当新物品为空时，此项属性为None """
        return self.mArgs.get("newArmorDict")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家 entityId """
        return self.mArgs.get("playerId")

class OnOffhandItemChangedServerEvent(object):
    """ [服务端] 触发时机：玩家切换副手物品时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldItemDict(self):
        # type: () -> dict | None
        """ 旧物品的物品信息字典，当旧物品为空时，此项属性为None """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict | None
        """ 新物品的物品信息字典，当新物品为空时，此项属性为None """
        return self.mArgs.get("newItemDict")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家 entityId """
        return self.mArgs.get("playerId")

class OnPlayerActiveShieldServerEvent(object):
    """ [服务端] 触发时机：玩家激活/取消激活盾牌触发的事件。包括玩家持盾进入潜行状态，以及在潜行状态切换盾牌（切换耐久度不同的相同盾牌不会触发） """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def isActive(self):
        # type: () -> bool
        """ True:尝试激活,False:尝试取消激活 """
        return self.mArgs.get("isActive")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 盾牌物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancelable(self):
        # type: () -> bool
        """ 是否可以取消。如果玩家在潜行状态切换盾牌，则无法取消 """
        return self.mArgs.get("cancelable")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消这次激活 """
        return self.mArgs.get("cancel")

class OnPlayerBlockedByShieldAfterServerEvent(object):
    """ [服务端] 触发时机：玩家使用盾牌抵挡伤害之后触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def sourceId(self):
        # type: () -> str
        """ 伤害来源实体Id，没有实体返回"-1" """
        return self.mArgs.get("sourceId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 盾牌物品字典物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def damage(self):
        # type: () -> float
        """ 抵挡的伤害数值 """
        return self.mArgs.get("damage")

class OnPlayerBlockedByShieldBeforeServerEvent(object):
    """ [服务端] 触发时机：玩家使用盾牌抵挡伤害之前触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def sourceId(self):
        # type: () -> str
        """ 伤害来源实体Id，没有实体返回"-1" """
        return self.mArgs.get("sourceId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 盾牌物品字典物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def damage(self):
        # type: () -> float
        """ 抵挡的伤害数值 """
        return self.mArgs.get("damage")

class PlayerDropItemServerEvent(object):
    """ [服务端] 触发时机：玩家丢弃物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def itemEntityId(self):
        # type: () -> str
        """ 物品entityId """
        return self.mArgs.get("itemEntityId")

class PlayerPickupArrowServerEvent(object):
    """ [服务端] 玩家即将捡起抛射物时触发，包括使用"netease:pick_up"的自定义抛射物 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def arrowId(self):
        # type: () -> str
        """ 抛射物Id """
        return self.mArgs.get("arrowId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 触碰的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True时将取消本次拾取 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def pickupDelay(self):
        # type: () -> int
        """ 取消拾取后重新设置该物品的拾取cd，小于15帧将视作15帧，大于等于97813帧将视作无法拾取，每秒30帧 """
        return self.mArgs.get("pickupDelay")

    @pickupDelay.setter
    def pickupDelay(self, value):
        self.mArgs["pickupDelay"] = value

class PlayerTryAddCustomContainerItemClientEvent(object):
    """ [客户端] 玩家尝试将物品添加到自定义容器时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试添加物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 放入容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次放入自定义容器的操作 """
        return self.mArgs.get("cancel")

class PlayerTryAddCustomContainerItemServerEvent(object):
    """ [服务端] 玩家尝试将物品添加到自定义容器时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试添加物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 放入容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

class PlayerTryDropItemClientEvent(object):
    """ [客户端] 触发时机：玩家丢弃物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 物品dict """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消此次操作 """
        return self.mArgs.get("cancel")

class PlayerTryPutCustomContainerItemClientEvent(object):
    """ [客户端] 玩家尝试将物品放入自定义容器时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试放入物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 放入容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次放入自定义容器的操作 """
        return self.mArgs.get("cancel")

class PlayerTryPutCustomContainerItemServerEvent(object):
    """ [服务端] 玩家尝试将物品放入自定义容器时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试放入物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 放入容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次放入自定义容器的操作 """
        return self.mArgs.get("cancel")

class PlayerTryRemoveCustomContainerItemClientEvent(object):
    """ [客户端] 玩家尝试从自定义容器中移除物品时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试移除物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 目标容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该操作，默认为false，事件中改为true时拒绝此次移除物品的操作 """
        return self.mArgs.get("cancel")

class PlayerTryRemoveCustomContainerItemServerEvent(object):
    """ [服务端] 玩家尝试从自定义容器中移除物品时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def itemDict(self):
        # type: () -> dict
        """ 尝试移除物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def collectionName(self):
        # type: () -> str
        """ 放入容器名称，对应容器json中"custom_description"字段 """
        return self.mArgs.get("collectionName")

    @property
    def collectionType(self):
        # type: () -> str
        """ 放入容器类型，目前仅支持netease_container和netease_ui_container """
        return self.mArgs.get("collectionType")

    @property
    def collectionIndex(self):
        # type: () -> int
        """ 目标容器索引 """
        return self.mArgs.get("collectionIndex")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def x(self):
        # type: () -> int
        """ 容器方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 容器方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 容器方块z坐标 """
        return self.mArgs.get("z")

class ServerItemTryUseEvent(object):
    """ [服务端] 玩家点击右键尝试使用物品时服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设为True可取消物品的使用 """
        return self.mArgs.get("cancel")

class ServerItemUseOnEvent(object):
    """ [服务端] 玩家在对方块使用物品之前服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def x(self):
        # type: () -> int
        """ 方块 x 坐标值 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块 y 坐标值 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块 z 坐标值 """
        return self.mArgs.get("z")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier """
        return self.mArgs.get("blockName")

    @property
    def blockAuxValue(self):
        # type: () -> int
        """ 方块的附加值 """
        return self.mArgs.get("blockAuxValue")

    @property
    def face(self):
        # type: () -> int
        """ 点击方块的面，参考Facing枚举 """
        return self.mArgs.get("face")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def clickX(self):
        # type: () -> float
        """ 点击点的x比例位置 """
        return self.mArgs.get("clickX")

    @property
    def clickY(self):
        # type: () -> float
        """ 点击点的y比例位置 """
        return self.mArgs.get("clickY")

    @property
    def clickZ(self):
        # type: () -> float
        """ 点击点的z比例位置 """
        return self.mArgs.get("clickZ")

    @property
    def ret(self):
        # type: () -> bool
        """ 设为True可取消物品的使用 """
        return self.mArgs.get("ret")

class ServerPlayerTryTouchEvent(object):
    """ [服务端] 玩家即将捡起物品时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def entityId(self):
        # type: () -> str
        """ 物品实体的Id """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 触碰的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True时将取消本次拾取 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def pickupDelay(self):
        # type: () -> int
        """ 取消拾取后重新设置该物品的拾取cd，小于15帧将视作15帧，大于等于97813帧将视作无法拾取 """
        return self.mArgs.get("pickupDelay")

    @pickupDelay.setter
    def pickupDelay(self, value):
        self.mArgs["pickupDelay"] = value

class ShearsUseToBlockBeforeServerEvent(object):
    """ [服务端] 触发时机：实体手持剪刀对方块使用时，有剪刀特殊效果的方块会在服务端线程触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blockX(self):
        # type: () -> int
        """ 方块位置x """
        return self.mArgs.get("blockX")

    @property
    def blockY(self):
        # type: () -> int
        """ 方块位置y """
        return self.mArgs.get("blockY")

    @property
    def blockZ(self):
        # type: () -> int
        """ 方块位置z """
        return self.mArgs.get("blockZ")

    @property
    def blockName(self):
        # type: () -> str
        """ 方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockName")

    @property
    def auxData(self):
        # type: () -> int
        """ 方块附加值 """
        return self.mArgs.get("auxData")

    @property
    def dropName(self):
        # type: () -> str
        """ 触发剪刀效果的掉落物identifier，包含命名空间及名称 """
        return self.mArgs.get("dropName")

    @property
    def dropCount(self):
        # type: () -> int
        """ 触发剪刀效果的掉落物数量 """
        return self.mArgs.get("dropCount")

    @property
    def entityId(self):
        # type: () -> str
        """ 触发剪刀效果的实体id，目前仅玩家会触发 """
        return self.mArgs.get("entityId")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 玩家触发时的维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancelShears(self):
        # type: () -> bool
        """ 是否取消剪刀效果 """
        return self.mArgs.get("cancelShears")

class StartUsingItemClientEvent(object):
    """ [客户端] 玩家使用物品（目前仅支持Bucket（奶桶）、Trident（三叉戟）、RangedWeapon（弓）、Food（食物）、Potion（药水）、Crossbow（弩））时抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

class StopUsingItemClientEvent(object):
    """ [客户端] 玩家停止使用物品（目前仅支持Bucket（奶桶）、Trident（三叉戟）、RangedWeapon（弓）、Food（食物）、Potion（药水）、Crossbow（弩））时抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 使用的物品的物品信息字典 """
        return self.mArgs.get("itemDict")

class UIContainerItemChangedServerEvent(object):
    """ [服务端] 合成容器物品发生变化时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def slot(self):
        # type: () -> int
        """ 容器槽位，含义见：容器类型枚举 """
        return self.mArgs.get("slot")

    @property
    def oldItemDict(self):
        # type: () -> dict
        """ 旧物品，格式参考物品信息字典 """
        return self.mArgs.get("oldItemDict")

    @property
    def newItemDict(self):
        # type: () -> dict
        """ 生成的物品，格式参考物品信息字典 """
        return self.mArgs.get("newItemDict")
