# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class lobbyGoodBuySucServerEvent(object):
    """ [服务端] 玩家登录联机大厅服务器，或者联机大厅游戏内购买商品时触发。如果是玩家登录，触发时玩家客户端已经触发了UiInitFinished事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def eid(self):
        # type: () -> str
        """ 购买商品的玩家实体id """
        return self.mArgs.get("eid")

    @property
    def buyItem(self):
        # type: () -> bool
        """ 玩家登录时为False，玩家购买了商品时为True """
        return self.mArgs.get("buyItem")
