# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class AddExpEvent(object):
    """ [服务端] 触发时机：当玩家增加经验时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

    @property
    def addExp(self):
        # type: () -> int
        """ 增加的经验值 """
        return self.mArgs.get("addExp")

class AddLevelEvent(object):
    """ [服务端] 触发时机：当玩家升级时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

    @property
    def addLevel(self):
        # type: () -> int
        """ 增加的等级值 """
        return self.mArgs.get("addLevel")

    @property
    def newLevel(self):
        # type: () -> int
        """ 新的等级 """
        return self.mArgs.get("newLevel")

class CameraMotionStartClientEvent(object):
    """ [客户端] 相机运动器开始事件。相机添加运动器后，运动器开始运行时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def motionId(self):
        # type: () -> int
        """ 运动器id """
        return self.mArgs.get("motionId")

class CameraMotionStopClientEvent(object):
    """ [客户端] 相机运动器停止事件。相机添加运动器并开始运行后，运动器自动停止时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def motionId(self):
        # type: () -> int
        """ 运动器id """
        return self.mArgs.get("motionId")

    @property
    def remove(self):
        # type: () -> bool
        """ 是否移除该运动器，设置为False则保留，默认为True，即运动器停止后自动移除 """
        return self.mArgs.get("remove")

    @remove.setter
    def remove(self, value):
        self.mArgs["remove"] = value

class ChangeLevelUpCostServerEvent(object):
    """ [服务端] 触发时机：获取玩家下一个等级升级经验时，用于重载玩家的升级经验，每个等级在重置之前都只会触发一次 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def level(self):
        # type: () -> int
        """ 玩家当前等级 """
        return self.mArgs.get("level")

    @property
    def levelUpCostExp(self):
        # type: () -> int
        """ 当前等级升级到下个等级需要的经验值，当设置升级经验小于1时会被强制调整到1 """
        return self.mArgs.get("levelUpCostExp")

    @levelUpCostExp.setter
    def levelUpCostExp(self, value):
        self.mArgs["levelUpCostExp"] = value

    @property
    def changed(self):
        # type: () -> bool
        """ 设置为True，重载玩家升级经验才会生效 """
        return self.mArgs.get("changed")

    @changed.setter
    def changed(self, value):
        self.mArgs["changed"] = value

class DimensionChangeClientEvent(object):
    """ [客户端] 玩家维度改变时客户端抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 维度改变前的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 维度改变后的维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def fromX(self):
        # type: () -> float
        """ 改变前的位置x """
        return self.mArgs.get("fromX")

    @property
    def fromY(self):
        # type: () -> float
        """ 改变前的位置Y """
        return self.mArgs.get("fromY")

    @property
    def fromZ(self):
        # type: () -> float
        """ 改变前的位置Z """
        return self.mArgs.get("fromZ")

    @property
    def toX(self):
        # type: () -> float
        """ 改变后的位置x """
        return self.mArgs.get("toX")

    @property
    def toY(self):
        # type: () -> float
        """ 改变后的位置Y """
        return self.mArgs.get("toY")

    @property
    def toZ(self):
        # type: () -> float
        """ 改变后的位置Z """
        return self.mArgs.get("toZ")

class DimensionChangeFinishClientEvent(object):
    """ [客户端] 玩家维度改变完成后客户端抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 维度改变前的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 维度改变后的维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def toPos(self):
        # type: () -> tuple[float, float, float]
        """ 改变后的位置x,y,z,其中y值为脚底加上角色的身高值 """
        return self.mArgs.get("toPos")

class DimensionChangeFinishServerEvent(object):
    """ [服务端] 玩家维度改变完成后服务端抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 维度改变前的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 维度改变后的维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def toPos(self):
        # type: () -> tuple[float, float, float]
        """ 改变后的位置x,y,z,其中y值为脚底加上角色的身高值 """
        return self.mArgs.get("toPos")

class DimensionChangeServerEvent(object):
    """ [服务端] 玩家维度改变时服务端抛出 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def fromDimensionId(self):
        # type: () -> int
        """ 维度改变前的维度 """
        return self.mArgs.get("fromDimensionId")

    @property
    def toDimensionId(self):
        # type: () -> int
        """ 维度改变后的维度 """
        return self.mArgs.get("toDimensionId")

    @property
    def fromX(self):
        # type: () -> float
        """ 改变前的位置x """
        return self.mArgs.get("fromX")

    @property
    def fromY(self):
        # type: () -> float
        """ 改变前的位置Y """
        return self.mArgs.get("fromY")

    @property
    def fromZ(self):
        # type: () -> float
        """ 改变前的位置Z """
        return self.mArgs.get("fromZ")

    @property
    def toX(self):
        # type: () -> float
        """ 改变后的位置x """
        return self.mArgs.get("toX")

    @property
    def toY(self):
        # type: () -> float
        """ 改变后的位置Y """
        return self.mArgs.get("toY")

    @property
    def toZ(self):
        # type: () -> float
        """ 改变后的位置Z """
        return self.mArgs.get("toZ")

class ExtinguishFireClientEvent(object):
    """ [客户端] 玩家扑灭火焰时触发。下雨，倒水等方式熄灭火焰不会触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def pos(self):
        # type: () -> tuple[float, float, float]
        """ 火焰方块的坐标 """
        return self.mArgs.get("pos")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可阻止玩家扑灭火焰。需要与ExtinguishFireServerEvent一起修改。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class ExtinguishFireServerEvent(object):
    """ [服务端] 玩家扑灭火焰时触发。下雨，倒水等方式熄灭火焰不会触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def pos(self):
        # type: () -> tuple[float, float, float]
        """ 火焰方块的坐标 """
        return self.mArgs.get("pos")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 修改为True时，可阻止玩家扑灭火焰。需要与ExtinguishFireClientEvent一起修改。 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class GameTypeChangedClientEvent(object):
    """ [客户端] 个人游戏模式发生变化时客户端触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def oldGameType(self):
        # type: () -> int
        """ 切换前的游戏模式 """
        return self.mArgs.get("oldGameType")

    @property
    def newGameType(self):
        # type: () -> int
        """ 切换后的游戏模式 """
        return self.mArgs.get("newGameType")

class GameTypeChangedServerEvent(object):
    """ [服务端] 当默认游戏模式或个人游戏模式发生变化时服务端触发，如果个人游戏模式不为默认时，修改默认游戏模式也会同时修改个人游戏模式，此时会触发两次该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id，SetDefaultGameType接口改变游戏模式时该参数为空字符串 """
        return self.mArgs.get("playerId")

    @property
    def oldGameType(self):
        # type: () -> int
        """ 切换前的游戏模式 """
        return self.mArgs.get("oldGameType")

    @property
    def newGameType(self):
        # type: () -> int
        """ 切换后的游戏模式 """
        return self.mArgs.get("newGameType")

class MountTamingEvent(object):
    """ [服务端] 玩家通过骑乘驯服生物后触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def eid(self):
        # type: () -> str
        """ 生物id """
        return self.mArgs.get("eid")

    @property
    def pid(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("pid")

class OnLocalPlayerActionClientEvent(object):
    """ [客户端] 玩家动作事件，当本地玩家开始/停止某些动作时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def actionType(self):
        # type: () -> int
        """ 动作事件枚举，详见Minecraft枚举值文档的PlayerActionType """
        return self.mArgs.get("actionType")

class OnLocalPlayerStartJumpClientEvent(object):
    """ [客户端] 本地玩家开始跳跃时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class OnPlayerActionServerEvent(object):
    """ [服务端] 玩家动作事件，当玩家开始/停止某些动作时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def actionType(self):
        # type: () -> int
        """ 动作事件枚举，详见Minecraft枚举值文档的PlayerActionType """
        return self.mArgs.get("actionType")

class OnPlayerHitBlockClientEvent(object):
    """ [客户端] 触发时机：通过OpenPlayerHitBlockDetection打开方块碰撞检测后，当玩家碰撞到方块时触发该事件。玩家着地时会触发OnGroundClientEvent，而不是该事件。客户端和服务端分别作碰撞检测，可能两个事件返回的结果略有差异。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 碰撞到方块的玩家Id """
        return self.mArgs.get("playerId")

    @property
    def posX(self):
        # type: () -> int
        """ 碰撞方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 碰撞方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 碰撞方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockId(self):
        # type: () -> str
        """ 碰撞方块的identifier """
        return self.mArgs.get("blockId")

    @property
    def auxValue(self):
        # type: () -> int
        """ 碰撞方块的附加值 """
        return self.mArgs.get("auxValue")

class OnPlayerHitBlockServerEvent(object):
    """ [服务端] 触发时机：通过OpenPlayerHitBlockDetection打开方块碰撞检测后，当玩家碰撞到方块时触发该事件。监听玩家着地请使用客户端的OnGroundClientEvent。客户端和服务端分别作碰撞检测，可能两个事件返回的略有差异。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 碰撞到方块的玩家Id """
        return self.mArgs.get("playerId")

    @property
    def posX(self):
        # type: () -> int
        """ 碰撞方块x坐标 """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> int
        """ 碰撞方块y坐标 """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> int
        """ 碰撞方块z坐标 """
        return self.mArgs.get("posZ")

    @property
    def blockId(self):
        # type: () -> str
        """ 碰撞方块的identifier """
        return self.mArgs.get("blockId")

    @property
    def auxValue(self):
        # type: () -> int
        """ 碰撞方块的附加值 """
        return self.mArgs.get("auxValue")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class PerspChangeClientEvent(object):
    """ [客户端] 视角切换时会触发的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def _from(self):
        # type: () -> int
        """ 切换前的视角 """
        return self.mArgs.get("from")

    @property
    def to(self):
        # type: () -> int
        """ 切换后的视角 """
        return self.mArgs.get("to")

class PlayerAttackEntityEvent(object):
    """ [双端] 触发时机：当玩家攻击时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def victimId(self):
        # type: () -> str
        """ 受击者id """
        return self.mArgs.get("victimId")

    @property
    def damage(self):
        # type: () -> float
        """ 伤害值：引擎传过来的值是0 允许脚本层修改为其他数 """
        return self.mArgs.get("damage")

    @damage.setter
    def damage(self, value):
        self.mArgs["damage"] = value

    @property
    def isValid(self):
        # type: () -> int
        """ 脚本是否设置伤害值：1表示是；0 表示否 """
        return self.mArgs.get("isValid")

    @isValid.setter
    def isValid(self, value):
        self.mArgs["isValid"] = value

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消该次攻击，默认不取消 """
        return self.mArgs.get("cancel")

    @property
    def isKnockBack(self):
        # type: () -> bool
        """ 是否支持击退效果，默认支持，当不支持时将屏蔽武器击退附魔效果 """
        return self.mArgs.get("isKnockBack")

    @property
    def isCrit(self):
        # type: () -> bool
        """ 本次攻击是否产生暴击,不支持修改 """
        return self.mArgs.get("isCrit")

    @isCrit.setter
    def isCrit(self, value):
        self.mArgs["isCrit"] = value

class PlayerCheatSpinAttackServerEvent(object):
    """ [客户端] 触发时机：玩家开始/结束快速旋转攻击并且不符合发送快速旋转攻击条件时触发（装备激流附魔的三叉戟、在水中或雨中，且未骑乘） """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家的entityId """
        return self.mArgs.get("playerId")

    @property
    def isStart(self):
        # type: () -> bool
        """ True时代表开始快速旋转攻击；False时代表结束快速旋转攻击 """
        return self.mArgs.get("isStart")

class PlayerDieEvent(object):
    """ [服务端] 触发时机：当玩家死亡时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

    @property
    def attacker(self):
        # type: () -> str
        """ 伤害来源id """
        return self.mArgs.get("attacker")

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

class PlayerDoInteractServerEvent(object):
    """ [服务端] 玩家与有minecraft:interact组件的生物交互时触发该事件，例如玩家手持空桶对牛挤奶、玩家手持打火石点燃苦力怕 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 交互时使用物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def interactEntityId(self):
        # type: () -> str
        """ 交互的生物entityId """
        return self.mArgs.get("interactEntityId")

class PlayerEatFoodServerEvent(object):
    """ [服务端] 触发时机：玩家吃下食物时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家Id """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 食物物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def hunger(self):
        # type: () -> int
        """ 食物增加的饥饿值，可修改 """
        return self.mArgs.get("hunger")

    @hunger.setter
    def hunger(self, value):
        self.mArgs["hunger"] = value

    @property
    def nutrition(self):
        # type: () -> float
        """ 食物的营养价值，回复饱和度 = 食物增加的饥饿值 * 食物的营养价值 * 2，饱和度最大不超过当前饥饿值，可修改 """
        return self.mArgs.get("nutrition")

    @nutrition.setter
    def nutrition(self, value):
        self.mArgs["nutrition"] = value

class PlayerFeedEntityServerEvent(object):
    """ [服务端] 玩家喂养生物时触发，例如玩家手持小麦喂养牛、玩家手持胡萝卜喂养幼年猪。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 主动喂养生物的玩家的唯一ID """
        return self.mArgs.get("playerId")

    @property
    def entityId(self):
        # type: () -> str
        """ 被喂养生物的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 当前玩家手持物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消触发，默认为False，若设为True，可阻止触发后续的生物喂养逻辑 """
        return self.mArgs.get("cancel")

class PlayerHungerChangeServerEvent(object):
    """ [服务端] 玩家饥饿度变化时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def hungerBefore(self):
        # type: () -> float
        """ 变化前的饥饿度 """
        return self.mArgs.get("hungerBefore")

    @property
    def hunger(self):
        # type: () -> float
        """ 变化后的饥饿度 """
        return self.mArgs.get("hunger")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消饥饿度变化 """
        return self.mArgs.get("cancel")

class PlayerHurtEvent(object):
    """ [服务端] 触发时机：当玩家受伤害前触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 受击玩家id """
        return self.mArgs.get("id")

    @property
    def attacker(self):
        # type: () -> str
        """ 伤害来源实体id，若没有实体攻击，例如高空坠落，id为-1 """
        return self.mArgs.get("attacker")

    @property
    def customTag(self):
        # type: () -> str
        """ 使用Hurt接口传入的自定义伤害类型 """
        return self.mArgs.get("customTag")

    @property
    def cause(self):
        # type: () -> str
        """ 伤害来源，详见Minecraft枚举值文档的ActorDamageCause """
        return self.mArgs.get("cause")

class PlayerInteractServerEvent(object):
    """ [服务端] 触发时机：玩家可以与实体交互时。如果是鼠标控制模式，则当准心对着实体时触发。如果是触屏模式，则触发时机与屏幕下方的交互按钮显示的时机相同。玩家真正与实体发生交互的事件见PlayerDoInteractServerEvent """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消触发，默认为False，若设为True，可阻止触发后续的实体交互事件 """
        return self.mArgs.get("cancel")

    @property
    def playerId(self):
        # type: () -> str
        """ 主动与实体互动的玩家的唯一ID """
        return self.mArgs.get("playerId")

    @property
    def itemDict(self):
        # type: () -> dict
        """ 当前玩家手持物品的物品信息字典 """
        return self.mArgs.get("itemDict")

    @property
    def victimId(self):
        # type: () -> str
        """ 被动的实体的唯一ID """
        return self.mArgs.get("victimId")

class PlayerNamedEntityServerEvent(object):
    """ [服务端] 玩家用命名牌重命名实体时触发，例如玩家手持命名牌对羊修改名字、玩家手持命名牌对盔甲架修改名字。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 主动命名实体的玩家的唯一ID """
        return self.mArgs.get("playerId")

    @property
    def entityId(self):
        # type: () -> str
        """ 被命名实体的唯一ID """
        return self.mArgs.get("entityId")

    @property
    def preName(self):
        # type: () -> str
        """ 实体当前的名字 """
        return self.mArgs.get("preName")

    @property
    def afterName(self):
        # type: () -> str
        """ 实体重命名后的名字 """
        return self.mArgs.get("afterName")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消触发，默认为False，若设为True，可阻止触发后续的实体命名逻辑 """
        return self.mArgs.get("cancel")

class PlayerPermissionChangeClientEvent(object):
    """ [客户端] 玩家权限变更事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def causePlayerId(self):
        # type: () -> str
        """ 发起者id """
        return self.mArgs.get("causePlayerId")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def oldPermission(self):
        # type: () -> dict
        """ 变化前的权限字典 """
        return self.mArgs.get("oldPermission")

    @property
    def newPermission(self):
        # type: () -> dict
        """ 变化后的权限字典 """
        return self.mArgs.get("newPermission")

    @property
    def changeCause(self):
        # type: () -> int
        """ 变化原因，详见Minecraft枚举值文档的PermissionChangeCause """
        return self.mArgs.get("changeCause")

class PlayerPermissionChangeServerEvent(object):
    """ [服务端] 玩家权限变更事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def causePlayerId(self):
        # type: () -> str
        """ 发起者id """
        return self.mArgs.get("causePlayerId")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def oldPermission(self):
        # type: () -> dict
        """ 变化前的权限字典 """
        return self.mArgs.get("oldPermission")

    @property
    def newPermission(self):
        # type: () -> dict
        """ 变化后的权限字典 """
        return self.mArgs.get("newPermission")

    @property
    def changeCause(self):
        # type: () -> int
        """ 变化原因，详见Minecraft枚举值文档的PermissionChangeCause """
        return self.mArgs.get("changeCause")

    @property
    def cancel(self):
        # type: () -> bool
        """ 为true时，取消本次权限变更 """
        return self.mArgs.get("cancel")

class PlayerRespawnEvent(object):
    """ [服务端] 触发时机：玩家复活时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

class PlayerRespawnFinishServerEvent(object):
    """ [服务端] 触发时机：玩家复活完毕时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class PlayerSleepServerEvent(object):
    """ [服务端] 玩家使用床睡觉成功 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class PlayerSpinAttackServerEvent(object):
    """ [客户端] 触发时机：玩家开始/结束快速旋转攻击时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家的entityId """
        return self.mArgs.get("playerId")

    @property
    def isInWaterOrRain(self):
        # type: () -> bool
        """ 是否在水中或雨中 """
        return self.mArgs.get("isInWaterOrRain")

    @property
    def isRiding(self):
        # type: () -> bool
        """ 是否骑乘状态 """
        return self.mArgs.get("isRiding")

    @property
    def isStart(self):
        # type: () -> bool
        """ True时代表开始快速旋转攻击；False时代表结束快速旋转攻击 """
        return self.mArgs.get("isStart")

class PlayerStopSleepServerEvent(object):
    """ [服务端] 玩家停止睡觉 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class PlayerTeleportEvent(object):
    """ [服务端] 触发时机：当玩家传送时触发该事件，如：玩家使用末影珍珠或tp指令时。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

class PlayerTrySleepServerEvent(object):
    """ [服务端] 玩家尝试使用床睡觉 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消（开发者传入） """
        return self.mArgs.get("cancel")

class ServerPlayerGetExperienceOrbEvent(object):
    """ [服务端] 触发时机：玩家获取经验球时触发的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def experienceValue(self):
        # type: () -> int
        """ 经验球经验值 """
        return self.mArgs.get("experienceValue")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消（开发者传入） """
        return self.mArgs.get("cancel")

class StoreBuySuccServerEvent(object):
    """ [服务端] 触发时机:玩家游戏内购买商品时服务端抛出的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 购买商品的玩家实体id """
        return self.mArgs.get("playerId")

class UpdatePlayerSkinClientEvent(object):
    """ [客户端] 触发时机：玩家加入游戏或通过更衣室局内换肤后 同步皮肤信息至客户端后触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 更换皮肤的玩家id """
        return self.mArgs.get("playerId")
