# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class OnMusicStopClientEvent(object):
    """ [客户端] 音乐停止时，当玩家调用StopCustomMusic来停止自定义背景音乐时，会触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def musicName(self):
        # type: () -> str
        """ 音乐名称 """
        return self.mArgs.get("musicName")

class PlayMusicClientEvent(object):
    """ [客户端] 播放背景音乐时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 即资源包中sounds/music_definitions.json中的event_name，并且对应sounds/sound_definitions.json中的key """
        return self.mArgs.get("name")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设为True可屏蔽该次音效播放 """
        return self.mArgs.get("cancel")

class PlaySoundClientEvent(object):
    """ [客户端] 播放场景音效或UI音效时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 即资源包中sounds/sound_definitions.json中的key """
        return self.mArgs.get("name")

    @property
    def pos(self):
        # type: () -> tuple[float, float, float]
        """ 音效播放的位置。UI音效为(0,0,0) """
        return self.mArgs.get("pos")

    @property
    def volume(self):
        # type: () -> float
        """ 音量，范围为0-1 """
        return self.mArgs.get("volume")

    @property
    def pitch(self):
        # type: () -> float
        """ 播放速度，正常速度为1 """
        return self.mArgs.get("pitch")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设为True可屏蔽该次音效播放 """
        return self.mArgs.get("cancel")
