# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class AchievementButtonMovedClientEvent(object):
    """ [客户端] 触发时机：使用自定义成就系统的时，拖动成就入口结束时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldPosition(self):
        # type: () -> tuple[float, float]
        """ 移动前该控件相对父节点的坐标信息，第一项为横轴，第二项为纵轴 """
        return self.mArgs.get("oldPosition")

    @property
    def newPosition(self):
        # type: () -> tuple[float, float]
        """ 移动后该控件相对父节点的坐标信息，第一项为横轴，第二项为纵轴 """
        return self.mArgs.get("newPosition")

class ClientChestCloseEvent(object):
    """ [客户端] 关闭箱子界面时触发，包括小箱子，合并后大箱子和末影箱(实体容器不属于方块，不会触发该事件) """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class ClientChestOpenEvent(object):
    """ [客户端] 打开箱子界面时触发，包括小箱子，合并后大箱子和末影箱(实体容器不属于方块，不会触发该事件) """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("playerId")

    @property
    def x(self):
        # type: () -> int
        """ 箱子位置x值 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 箱子位置y值 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 箱子位置z值 """
        return self.mArgs.get("z")

class ClientPlayerInventoryCloseEvent(object):
    """ [客户端] 关闭物品背包界面时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class ClientPlayerInventoryOpenEvent(object):
    """ [客户端] 打开物品背包界面时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def isCreative(self):
        # type: () -> bool
        """ 是否是创造模式背包界面 """
        return self.mArgs.get("isCreative")

    @property
    def cancel(self):
        # type: () -> bool
        """ 取消打开物品背包界面 """
        return self.mArgs.get("cancel")

class CloseNeteaseShopEvent(object):
    """ [客户端] 关闭商城界面时触发，包括脚本商城和Apollo插件商城 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class GridComponentSizeChangedClientEvent(object):
    """ [客户端] UI grid控件里格子重新排列时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def path(self):
        # type: () -> str
        """ grid网格所在的路径（从UI根节点算起） """
        return self.mArgs.get("path")

class HudButtonChangedClientEvent(object):
    """ [客户端] 当原生HUD按钮位置或大小发生改变时触发，例如玩家使用了自定义控件功能会触发，可在该事件中修改mod按钮的位置防止重叠 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def changedList(self):
        # type: () -> tuple[dict]
        """ 修改后的按钮列表 """
        return self.mArgs.get("changedList")

    @changedList.setter
    def changedList(self, value):
        self.mArgs["changedList"] = value

class OnItemSlotButtonClickedEvent(object):
    """ [客户端] 点击快捷栏、背包栏、盔甲栏、副手栏的物品槽时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def slotIndex(self):
        # type: () -> int
        """ 点击的物品槽的编号，编号对应位置详见[物品栏] """
        return self.mArgs.get("slotIndex")

class PlayerChatButtonClickClientEvent(object):
    """ [客户端] 玩家点击聊天按钮或回车键触发呼出聊天窗口时客户端抛出的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class PlayerInventoryOpenScriptServerEvent(object):
    """ [服务端] 某个客户端打开物品背包界面时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 客户端对应的玩家entity的唯一ID """
        return self.mArgs.get("playerId")

    @property
    def isCreative(self):
        # type: () -> bool
        """ 是否是创造模式背包界面 """
        return self.mArgs.get("isCreative")

class PopScreenAfterClientEvent(object):
    """ [客户端] screen移除触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def screenName(self):
        # type: () -> str
        """ UI名字 """
        return self.mArgs.get("screenName")

    @property
    def screenDef(self):
        # type: () -> str
        """ 包含命名空间的UI名字，格式为namespace.screenName """
        return self.mArgs.get("screenDef")

class PopScreenEvent(object):
    """ [客户端] screen移除触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def screenName(self):
        # type: () -> str
        """ UI名字 """
        return self.mArgs.get("screenName")

    @property
    def screenDef(self):
        # type: () -> str
        """ 包含命名空间的UI名字，格式为namespace.screenName """
        return self.mArgs.get("screenDef")

class PushScreenEvent(object):
    """ [客户端] screen创建触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def screenName(self):
        # type: () -> str
        """ UI名字 """
        return self.mArgs.get("screenName")

    @property
    def screenDef(self):
        # type: () -> str
        """ 包含命名空间的UI名字，格式为namespace.screenName """
        return self.mArgs.get("screenDef")

class ScreenSizeChangedClientEvent(object):
    """ [客户端] 改变屏幕大小时会触发的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def beforeX(self):
        # type: () -> float
        """ 屏幕大小改变前的宽度 """
        return self.mArgs.get("beforeX")

    @property
    def beforeY(self):
        # type: () -> float
        """ 屏幕大小改变前的高度 """
        return self.mArgs.get("beforeY")

    @property
    def afterX(self):
        # type: () -> float
        """ 屏幕大小改变后的宽度 """
        return self.mArgs.get("afterX")

    @property
    def afterY(self):
        # type: () -> float
        """ 屏幕大小改变后的高度 """
        return self.mArgs.get("afterY")

class UiInitFinished(object):
    """ [客户端] UI初始化框架完成,此时可以创建UI """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class UrgeShipEvent(object):
    """ [服务端] 玩家点击商城催促发货按钮时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")
