# -*- coding: utf-8 -*-
# Generated By QuMod McEventCodeGen.py

class AchievementCompleteEvent(object):
    """ [服务端] 玩家完成自定义成就时触发该事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def rootNodeId(self):
        # type: () -> str
        """ 所属的页面的根节点成就id """
        return self.mArgs.get("rootNodeId")

    @property
    def achievementId(self):
        # type: () -> str
        """ 达成的成就id """
        return self.mArgs.get("achievementId")

    @property
    def title(self):
        # type: () -> str
        """ 成就标题 """
        return self.mArgs.get("title")

    @property
    def description(self):
        # type: () -> str
        """ 成就描述 """
        return self.mArgs.get("description")

class AddEntityClientEvent(object):
    """ [客户端] 客户端侧创建新实体时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

    @property
    def posX(self):
        # type: () -> float
        """ 位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 位置z """
        return self.mArgs.get("posZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 实体维度 """
        return self.mArgs.get("dimensionId")

    @property
    def isBaby(self):
        # type: () -> bool
        """ 是否为幼儿 """
        return self.mArgs.get("isBaby")

    @property
    def engineTypeStr(self):
        # type: () -> str
        """ 实体类型 """
        return self.mArgs.get("engineTypeStr")

    @property
    def itemName(self):
        # type: () -> str
        """ 物品identifier（仅当物品实体时存在该字段） """
        return self.mArgs.get("itemName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 物品附加值（仅当物品实体时存在该字段） """
        return self.mArgs.get("auxValue")

class AddEntityServerEvent(object):
    """ [服务端] 服务端侧创建新实体，或实体从存档加载时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

    @property
    def posX(self):
        # type: () -> float
        """ 位置x """
        return self.mArgs.get("posX")

    @property
    def posY(self):
        # type: () -> float
        """ 位置y """
        return self.mArgs.get("posY")

    @property
    def posZ(self):
        # type: () -> float
        """ 位置z """
        return self.mArgs.get("posZ")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 实体维度 """
        return self.mArgs.get("dimensionId")

    @property
    def isBaby(self):
        # type: () -> bool
        """ 是否为幼儿 """
        return self.mArgs.get("isBaby")

    @property
    def engineTypeStr(self):
        # type: () -> str
        """ 实体类型，即实体identifier """
        return self.mArgs.get("engineTypeStr")

    @property
    def itemName(self):
        # type: () -> str
        """ 物品identifier（仅当物品实体时存在该字段） """
        return self.mArgs.get("itemName")

    @property
    def auxValue(self):
        # type: () -> int
        """ 物品附加值（仅当物品实体时存在该字段） """
        return self.mArgs.get("auxValue")

class AddPlayerAOIClientEvent(object):
    """ [客户端] 玩家加入游戏时视野内存在其他玩家，或者其余玩家进入当前玩家视野时触发的事件，替换AddPlayerEvent """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class AddPlayerCreatedClientEvent(object):
    """ [客户端] 玩家进入当前玩家所在的区块AOI后，玩家皮肤数据异步加载完成后触发的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class AddServerPlayerEvent(object):
    """ [服务端] 触发时机：玩家加入时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

    @property
    def isTransfer(self):
        # type: () -> bool
        """ 是否是切服时进入服务器，仅用于Apollo。如果是True，则表示切服时加入服务器，若是False，则表示登录进入网络游戏 """
        return self.mArgs.get("isTransfer")

    @property
    def isReconnect(self):
        # type: () -> bool
        """ 是否是断线重连，仅用于Apollo。如果是True，则表示本次登录是断线重连，若是False，则表示本次是正常登录或者转服 """
        return self.mArgs.get("isReconnect")

    @property
    def isPeUser(self):
        # type: () -> bool
        """ 是否从手机端登录，仅用于Apollo。如果是True，则表示本次登录是从手机端登录，若是False，则表示本次登录是从PC端登录 """
        return self.mArgs.get("isPeUser")

    @property
    def transferParam(self):
        # type: () -> str
        """ 切服传入参数，仅用于Apollo。调用【TransferToOtherServer】或【TransferToOtherServerById】传入的切服参数 """
        return self.mArgs.get("transferParam")

    @property
    def uid(self):
        # type: () -> int
        """ 仅用于Apollo，玩家的netease uid，玩家的唯一标识 """
        return self.mArgs.get("uid")

    @property
    def proxyId(self):
        # type: () -> int
        """ 仅用于Apollo，当前客户端连接的proxy服务器id """
        return self.mArgs.get("proxyId")

class ChunkAcquireDiscardedClientEvent(object):
    """ [客户端] 触发时机：客户端区块即将被卸载时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 区块所在维度 """
        return self.mArgs.get("dimension")

    @property
    def chunkPosX(self):
        # type: () -> int
        """ 区块的x坐标，对应方块X坐标区间为[x * 16, x * 16 + 15] """
        return self.mArgs.get("chunkPosX")

    @property
    def chunkPosZ(self):
        # type: () -> int
        """ 区块的z坐标，对应方块Z坐标区间为[z * 16, z * 16 + 15] """
        return self.mArgs.get("chunkPosZ")

class ChunkAcquireDiscardedServerEvent(object):
    """ [服务端] 服务端区块即将被卸载时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 区块所在维度 """
        return self.mArgs.get("dimension")

    @property
    def chunkPosX(self):
        # type: () -> int
        """ 区块的x坐标，对应方块X坐标区间为[x * 16, x * 16 + 15] """
        return self.mArgs.get("chunkPosX")

    @property
    def chunkPosZ(self):
        # type: () -> int
        """ 区块的z坐标，对应方块Z坐标区间为[z * 16, z * 16 + 15] """
        return self.mArgs.get("chunkPosZ")

    @property
    def entities(self):
        # type: () -> list[str]
        """ 随区块卸载而从世界移除的实体id的列表。注意事件触发时已经无法获取到这些实体的信息，仅供脚本资源回收用。 """
        return self.mArgs.get("entities")

    @property
    def blockEntities(self):
        # type: () -> list[dict]
        """ 随区块卸载而从世界移除的自定义方块实体的坐标的列表，列表元素dict包含posX，posY，posZ三个int表示自定义方块实体的坐标，blockName表示方块的identifier，包含命名空间及名称。注意事件触发时已经无法获取到这些方块实体的信息，仅供脚本资源回收用。 """
        return self.mArgs.get("blockEntities")

class ChunkGeneratedServerEvent(object):
    """ [服务端] 触发时机：区块创建完成时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 该区块所在的维度 """
        return self.mArgs.get("dimension")

    @property
    def chunkPosX(self):
        # type: () -> int
        """ 区块的x坐标，对应方块X坐标区间为[x * 16, x * 16 + 15] """
        return self.mArgs.get("chunkPosX")

    @property
    def chunkPosZ(self):
        # type: () -> int
        """ 区块的z坐标，对应方块Z坐标区间为[z * 16, z * 16 + 15] """
        return self.mArgs.get("chunkPosZ")

    @property
    def blockEntityData(self):
        # type: () -> list[dict] | None
        """ 该区块中的自定义方块实体列表，通常是由自定义特征生成的自定义方块，没有自定义方块实体时该值为None """
        return self.mArgs.get("blockEntityData")

class ChunkLoadedClientEvent(object):
    """ [客户端] 触发时机：客户端区块加载完成时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 区块所在维度 """
        return self.mArgs.get("dimension")

    @property
    def chunkPosX(self):
        # type: () -> int
        """ 区块的x坐标，对应方块X坐标区间为[x * 16, x * 16 + 15] """
        return self.mArgs.get("chunkPosX")

    @property
    def chunkPosZ(self):
        # type: () -> int
        """ 区块的z坐标，对应方块Z坐标区间为[z * 16, z * 16 + 15] """
        return self.mArgs.get("chunkPosZ")

class ChunkLoadedServerEvent(object):
    """ [服务端] 触发时机：服务端区块加载完成时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimension(self):
        # type: () -> int
        """ 区块所在维度 """
        return self.mArgs.get("dimension")

    @property
    def chunkPosX(self):
        # type: () -> int
        """ 区块的x坐标，对应方块X坐标区间为[x * 16, x * 16 + 15] """
        return self.mArgs.get("chunkPosX")

    @property
    def chunkPosZ(self):
        # type: () -> int
        """ 区块的z坐标，对应方块Z坐标区间为[z * 16, z * 16 + 15] """
        return self.mArgs.get("chunkPosZ")

    @property
    def blockEntities(self):
        # type: () -> list[dict]
        """ 随区块加载而加载进世界的自定义方块实体的坐标的列表，列表元素dict包含posX，posY，posZ三个int表示自定义方块实体的坐标，blockName表示方块的identifier，包含命名空间及名称 """
        return self.mArgs.get("blockEntities")

class ClientLoadAddonsFinishServerEvent(object):
    """ [服务端] 触发时机：客户端mod加载完成时，服务端触发此事件。服务器可以使用此事件，往客户端发送数据给其初始化。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class CommandEvent(object):
    """ [服务端] 玩家请求执行指令时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 玩家ID """
        return self.mArgs.get("entityId")

    @property
    def command(self):
        # type: () -> str
        """ 指令字符串 """
        return self.mArgs.get("command")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消 """
        return self.mArgs.get("cancel")

class CustomCommandTriggerServerEvent(object):
    """ [服务端] 自定义命令触发事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def command(self):
        # type: () -> str
        """ 自定义命令名称，对应json中的name字段 """
        return self.mArgs.get("command")

    @property
    def args(self):
        # type: () -> list[dict]
        """ 自定义命令参数，详情见下方 """
        return self.mArgs.get("args")

    @property
    def variant(self):
        # type: () -> int
        """ 表示是哪条变体，范围[0, 9]，对应json中args键中的数字，未配置变体则为0 """
        return self.mArgs.get("variant")

    @property
    def origin(self):
        # type: () -> dict
        """ 触发源的信息，详情见下方 """
        return self.mArgs.get("origin")

    @property
    def return_failed(self):
        # type: () -> bool
        """ 设置自定义命令是否执行失败，默认为False，如果执行失败，返回信息以红色字体显示 """
        return self.mArgs.get("return_failed")

    @return_failed.setter
    def return_failed(self, value):
        self.mArgs["return_failed"] = value

    @property
    def return_msg_key(self):
        # type: () -> str
        """ 设置返回给玩家或命令方块的信息，也支持通过语言文件(.lang)定义，默认值为commands.custom.success(自定义命令执行成功) """
        return self.mArgs.get("return_msg_key")

    @return_msg_key.setter
    def return_msg_key(self, value):
        self.mArgs["return_msg_key"] = value

class DelServerPlayerEvent(object):
    """ [服务端] 触发时机：删除玩家时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("id")

    @property
    def isTransfer(self):
        # type: () -> bool
        """ 是否是切服时退出服务器，仅用于Apollo。如果是True，则表示切服时退出服务器；若是False，则表示退出网络游戏 """
        return self.mArgs.get("isTransfer")

    @property
    def uid(self):
        # type: () -> int
        """ 玩家的netease uid，玩家的唯一标识 """
        return self.mArgs.get("uid")

class EntityRemoveEvent(object):
    """ [服务端] 实体被删除时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("id")

class ExplosionServerEvent(object):
    """ [服务端] 当发生爆炸时触发。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def blocks(self):
        # type: () -> list[list[float | int, float | int, float | int, bool]]
        """ 爆炸导致的被破坏方块坐标(x,y,z)，cancel是一个bool值 """
        return self.mArgs.get("blocks")

    @property
    def victims(self):
        # type: () -> list | None
        """ 受伤实体id列表，当该爆炸创建者id为None时，victims也为None """
        return self.mArgs.get("victims")

    @property
    def sourceId(self):
        # type: () -> str | None
        """ 爆炸创建者id """
        return self.mArgs.get("sourceId")

    @property
    def explodePos(self):
        # type: () -> list
        """ 爆炸位置[x,y,z] """
        return self.mArgs.get("explodePos")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class GameRenderTickEvent(object):
    """ [客户端] 客户端渲染帧开始时触发该事件,一秒触发次数为当前的帧数 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class GlobalCommandServerEvent(object):
    """ [服务端] 服务端全局命令事件，包括聊天栏发送、SetCommand接口、命令方块（矿车）、行为包动画执行命令 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 执行命令的实体id, 如果没有此键，则是命令方块执行的命令 """
        return self.mArgs.get("entityId")

    @property
    def command(self):
        # type: () -> str
        """ 将要被执行的命令 """
        return self.mArgs.get("command")

    @property
    def blockPos(self):
        # type: () -> tuple[int, int, int]
        """ 执行命令的实体或方块的方块坐标 """
        return self.mArgs.get("blockPos")

    @property
    def dimension(self):
        # type: () -> int
        """ 执行命令的实体或方块所在维度id """
        return self.mArgs.get("dimension")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True可以取消命令执行 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class LoadClientAddonScriptsAfter(object):
    """ [客户端] 客户端加载mod完成事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class LoadServerAddonScriptsAfter(object):
    """ [服务端] 服务器加载完mod时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class NewOnEntityAreaEvent(object):
    """ [服务端] 触发时机：通过RegisterEntityAOIEvent注册过AOI事件后，当有实体进入或离开注册感应区域时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def name(self):
        # type: () -> str
        """ 注册感应区域名称 """
        return self.mArgs.get("name")

    @property
    def enteredEntities(self):
        # type: () -> list[str]
        """ 进入该感应区域的实体id列表 """
        return self.mArgs.get("enteredEntities")

    @property
    def leftEntities(self):
        # type: () -> list[str]
        """ 离开该感应区域的实体id列表 """
        return self.mArgs.get("leftEntities")

class OnCommandOutputClientEvent(object):
    """ [客户端] 当command命令有成功消息输出时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def command(self):
        # type: () -> str
        """ 命令名称 """
        return self.mArgs.get("command")

    @property
    def message(self):
        # type: () -> str
        """ 命令返回的消息 """
        return self.mArgs.get("message")

class OnCommandOutputServerEvent(object):
    """ [服务端] Command命令执行成功事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def command(self):
        # type: () -> str
        """ 命令名称 """
        return self.mArgs.get("command")

    @property
    def message(self):
        # type: () -> str
        """ 命令返回的消息 """
        return self.mArgs.get("message")

class OnContainerFillLoottableServerEvent(object):
    """ [服务端] 触发时机：随机奖励箱第一次打开根据loottable生成物品时 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def loottable(self):
        # type: () -> str
        """ 奖励箱子所读取的loottable的json路径 """
        return self.mArgs.get("loottable")

    @property
    def playerId(self):
        # type: () -> str
        """ 打开奖励箱子的玩家的playerId """
        return self.mArgs.get("playerId")

    @property
    def itemList(self):
        # type: () -> list
        """ 掉落物品列表，每个元素为一个itemDict，格式可参考物品信息字典 """
        return self.mArgs.get("itemList")

    @property
    def dirty(self):
        # type: () -> bool
        """ 默认为False，如果需要修改掉落列表需将该值设为True """
        return self.mArgs.get("dirty")

    @dirty.setter
    def dirty(self, value):
        self.mArgs["dirty"] = value

class OnLightningLevelChangeServerEvent(object):
    """ [服务端] 打雷强度发生改变 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldLevel(self):
        # type: () -> float
        """ 改变前的打雷强度 """
        return self.mArgs.get("oldLevel")

    @property
    def newLevel(self):
        # type: () -> float
        """ 改变后的打雷强度 """
        return self.mArgs.get("newLevel")

class OnLocalLightningLevelChangeServerEvent(object):
    """ [服务端] 独立维度天气打雷强度发生改变时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldLevel(self):
        # type: () -> float
        """ 改变前的打雷强度 """
        return self.mArgs.get("oldLevel")

    @property
    def newLevel(self):
        # type: () -> float
        """ 改变后的打雷强度 """
        return self.mArgs.get("newLevel")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 独立天气维度id """
        return self.mArgs.get("dimensionId")

class OnLocalPlayerStopLoading(object):
    """ [客户端] 触发时机：玩家进入存档，出生点地形加载完成时触发。该事件触发时可以进行切换维度的操作。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 加载完成的玩家id """
        return self.mArgs.get("playerId")

class OnLocalRainLevelChangeServerEvent(object):
    """ [服务端] 独立维度天气下雨强度发生改变时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldLevel(self):
        # type: () -> float
        """ 改变前的下雨强度 """
        return self.mArgs.get("oldLevel")

    @property
    def newLevel(self):
        # type: () -> float
        """ 改变后的下雨强度 """
        return self.mArgs.get("newLevel")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 独立天气维度id """
        return self.mArgs.get("dimensionId")

class OnRainLevelChangeServerEvent(object):
    """ [服务端] 下雨强度发生改变 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def oldLevel(self):
        # type: () -> float
        """ 改变前的下雨强度 """
        return self.mArgs.get("oldLevel")

    @property
    def newLevel(self):
        # type: () -> float
        """ 改变后的下雨强度 """
        return self.mArgs.get("newLevel")

class OnScriptTickClient(object):
    """ [客户端] 客户端tick事件,1秒30次 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class OnScriptTickServer(object):
    """ [服务端] 服务器tick时触发,1秒有30个tick """
    def __init__(self, args=None):
        self.mArgs = args or dict()

class PlaceNeteaseLargeFeatureServerEvent(object):
    """ [服务端] 触发时机：网易版大型结构即将生成时服务端抛出该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def pos(self):
        # type: () -> tuple
        """ 中心结构放置坐标(x, z) """
        return self.mArgs.get("pos")

    @property
    def rot(self):
        # type: () -> int
        """ 中心结构顺时针旋转角度 """
        return self.mArgs.get("rot")

    @property
    def depth(self):
        # type: () -> int
        """ 大型结构递归深度 """
        return self.mArgs.get("depth")

    @property
    def centerPool(self):
        # type: () -> str
        """ 中心池的identifier """
        return self.mArgs.get("centerPool")

    @property
    def ignoreFitInContext(self):
        # type: () -> bool
        """ 是否允许生成过结构的地方是否可以继续生成结构 """
        return self.mArgs.get("ignoreFitInContext")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True时可阻止该大型结构的放置 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class PlaceNeteaseStructureFeatureEvent(object):
    """ [服务端] 触发时机：首次生成地形时，结构特征即将生成时服务端抛出该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def structureName(self):
        # type: () -> str
        """ 结构名称，可修改 """
        return self.mArgs.get("structureName")

    @structureName.setter
    def structureName(self, value):
        self.mArgs["structureName"] = value

    @property
    def x(self):
        # type: () -> int
        """ 结构坐标最小方块所在的x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 结构坐标最小方块所在的y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 结构坐标最小方块所在的z坐标 """
        return self.mArgs.get("z")

    @property
    def biomeType(self):
        # type: () -> int
        """ 该feature所放置区块的生物群系类型 """
        return self.mArgs.get("biomeType")

    @property
    def biomeName(self):
        # type: () -> str
        """ 该feature所放置区块的生物群系名称 """
        return self.mArgs.get("biomeName")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def cancel(self):
        # type: () -> bool
        """ 设置为True时可阻止该结构的放置 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

class PlayerIntendLeaveServerEvent(object):
    """ [服务端] 触发时机：即将删除玩家时触发该事件，此时可以通过各种API获取玩家的当前状态。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class PlayerJoinMessageEvent(object):
    """ [服务端] 触发时机：准备显示“xxx加入游戏”的玩家登录提示文字时服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("id")

    @property
    def name(self):
        # type: () -> str
        """ 玩家昵称 """
        return self.mArgs.get("name")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否显示提示文字，允许修改。True：不显示提示 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def message(self):
        # type: () -> str
        """ 玩家加入游戏的提示文字，允许修改 """
        return self.mArgs.get("message")

    @message.setter
    def message(self, value):
        self.mArgs["message"] = value

class PlayerLeftMessageServerEvent(object):
    """ [服务端] 触发时机：准备显示“xxx离开游戏”的玩家离开提示文字时服务端抛出的事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 玩家实体id """
        return self.mArgs.get("id")

    @property
    def name(self):
        # type: () -> str
        """ 玩家昵称 """
        return self.mArgs.get("name")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否显示提示文字，允许修改。True：不显示提示 """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def message(self):
        # type: () -> str
        """ 玩家离开游戏的提示文字，允许修改 """
        return self.mArgs.get("message")

    @message.setter
    def message(self, value):
        self.mArgs["message"] = value

class RemoveEntityClientEvent(object):
    """ [客户端] 客户端侧实体被移除时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def id(self):
        # type: () -> str
        """ 移除的实体id """
        return self.mArgs.get("id")

class RemovePlayerAOIClientEvent(object):
    """ [客户端] 玩家离开当前玩家视野时触发的事件 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

class ServerChatEvent(object):
    """ [服务端] 玩家发送聊天信息时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def username(self):
        # type: () -> str
        """ 玩家名称 """
        return self.mArgs.get("username")

    @property
    def playerId(self):
        # type: () -> str
        """ 玩家id """
        return self.mArgs.get("playerId")

    @property
    def message(self):
        # type: () -> str
        """ 玩家发送的聊天消息内容 """
        return self.mArgs.get("message")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消这个聊天事件，若取消可以设置为True """
        return self.mArgs.get("cancel")

    @cancel.setter
    def cancel(self, value):
        self.mArgs["cancel"] = value

    @property
    def bChatById(self):
        # type: () -> bool
        """ 是否把聊天消息发送给指定在线玩家，而不是广播给所有在线玩家，若只发送某些玩家可以设置为True """
        return self.mArgs.get("bChatById")

    @bChatById.setter
    def bChatById(self, value):
        self.mArgs["bChatById"] = value

    @property
    def bForbid(self):
        # type: () -> bool
        """ 是否禁言，仅apollo可用。true：被禁言，玩家聊天会提示“你已被管理员禁言”。 """
        return self.mArgs.get("bForbid")

    @property
    def toPlayerIds(self):
        # type: () -> list[str]
        """ 接收聊天消息的玩家id列表，bChatById为True时生效 """
        return self.mArgs.get("toPlayerIds")

    @property
    def gameChatPrefix(self):
        # type: () -> str
        """ 设置当前玩家在网易聊天界面中的前缀，字数限制4，从字符串头部开始取。前缀文本输入非字符串格式时会被置为空。若cancel为True，会取消掉本次的前缀修改 """
        return self.mArgs.get("gameChatPrefix")

    @gameChatPrefix.setter
    def gameChatPrefix(self, value):
        self.mArgs["gameChatPrefix"] = value

    @property
    def gameChatPrefixColorR(self):
        # type: () -> float
        """ 设置当前玩家在网易聊天界面中前缀颜色rgb的r值，范围为[0,1]。颜色数值输入其他格式时会被置为0。若cancel为True，会取消掉本次的颜色修改 """
        return self.mArgs.get("gameChatPrefixColorR")

    @gameChatPrefixColorR.setter
    def gameChatPrefixColorR(self, value):
        self.mArgs["gameChatPrefixColorR"] = value

    @property
    def gameChatPrefixColorG(self):
        # type: () -> float
        """ 设置当前玩家在网易聊天界面中前缀颜色rgb的g值，范围为[0,1]。颜色数值输入其他格式时会被置为0。若cancel为True，会取消掉本次的颜色修改 """
        return self.mArgs.get("gameChatPrefixColorG")

    @gameChatPrefixColorG.setter
    def gameChatPrefixColorG(self, value):
        self.mArgs["gameChatPrefixColorG"] = value

    @property
    def gameChatPrefixColorB(self):
        # type: () -> float
        """ 设置当前玩家在网易聊天界面中前缀颜色rgb的b值，范围为[0,1]。颜色数值输入其他格式时会被置为0。若cancel为True，会取消掉本次的颜色修改 """
        return self.mArgs.get("gameChatPrefixColorB")

    @gameChatPrefixColorB.setter
    def gameChatPrefixColorB(self, value):
        self.mArgs["gameChatPrefixColorB"] = value

class ServerPostBlockPatternEvent(object):
    """ [服务端] 触发时机：用方块组合生成生物，生成生物之后触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 生成生物的id """
        return self.mArgs.get("entityId")

    @property
    def entityGenerated(self):
        # type: () -> str
        """ 生成生物的名字，如"minecraft:pig" """
        return self.mArgs.get("entityGenerated")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

class ServerPreBlockPatternEvent(object):
    """ [服务端] 触发时机：用方块组合生成生物，在放置最后一个组成方块时触发该事件。 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def enable(self):
        # type: () -> bool
        """ 是否允许继续生成。若设为False，可阻止生成生物 """
        return self.mArgs.get("enable")

    @property
    def x(self):
        # type: () -> int
        """ 方块x坐标 """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> int
        """ 方块y坐标 """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> int
        """ 方块z坐标 """
        return self.mArgs.get("z")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 维度id """
        return self.mArgs.get("dimensionId")

    @property
    def entityWillBeGenerated(self):
        # type: () -> str
        """ 即将生成生物的名字，如"minecraft:pig" """
        return self.mArgs.get("entityWillBeGenerated")

class ServerSpawnMobEvent(object):
    """ [服务端] 游戏内自动生成生物，以及使用api生成生物时触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()

    @property
    def entityId(self):
        # type: () -> str
        """ 实体id """
        return self.mArgs.get("entityId")

    @property
    def identifier(self):
        # type: () -> str
        """ 生成实体的命名空间 """
        return self.mArgs.get("identifier")

    @property
    def type(self):
        # type: () -> int
        """ 生成实体的类型，参考EntityType """
        return self.mArgs.get("type")

    @property
    def baby(self):
        # type: () -> bool
        """ 生成怪物是否是幼年怪 """
        return self.mArgs.get("baby")

    @property
    def x(self):
        # type: () -> float
        """ 生成实体坐标x """
        return self.mArgs.get("x")

    @property
    def y(self):
        # type: () -> float
        """ 生成实体坐标y """
        return self.mArgs.get("y")

    @property
    def z(self):
        # type: () -> float
        """ 生成实体坐标z """
        return self.mArgs.get("z")

    @property
    def dimensionId(self):
        # type: () -> int
        """ 生成实体的维度，默认值为0（0为主世界，1为地狱，2为末地） """
        return self.mArgs.get("dimensionId")

    @property
    def realIdentifier(self):
        # type: () -> str
        """ 生成实体的命名空间，通过MOD API生成的生物在这个参数也能获取到真正的命名空间，而不是以custom开头的 """
        return self.mArgs.get("realIdentifier")

    @property
    def cancel(self):
        # type: () -> bool
        """ 是否取消生成该实体 """
        return self.mArgs.get("cancel")

class UnLoadClientAddonScriptsBefore(object):
    """ [客户端] 客户端卸载mod之前触发 """
    def __init__(self, args=None):
        self.mArgs = args or dict()
